### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by nerd0ne** [vassbo/freeshow#10]
When I open freeshow it turns my computer screen black and does not let me open any other tabs.

**Comment by nerd0ne** [comment]
It will work for a split second than turn my screen black.

**Comment by nerd0ne** [comment]
I know why now, I think it is opening the projector screen to the same screen as the program,

**Comment by vassbo** [comment]
Hey, sorry about that. That is an issue on MAC right now, I will try to fix it. If you double click on the black window it should hide it (Yes, it is the projector screen/output window).
Try dragging on the mousepad with three fingers to switch workspace. Hope this helps.

**Comment by vassbo** [comment]
Actually on windows too. Just double click the black window to hide it! :)

**Comment by nerd0ne** [comment]
Thanks so much!
