### ISSUE TITLE
impossible to use the shortcuts

### ISSUE THREAD

**Issue by cenelson14** [vassbo/freeshow#102]
I can't use CMD c and CMD v or other shortcuts. I can't edit the files.

**Comment by vassbo** [comment]
Hi, this is a known problem on MAC, it will be fixed. You can copy/paste using the menu bar at the top.
What do you mean you can't edit the files?

**Comment by vassbo** [comment]
Should work in the latest version. Let me know it there still are some issues!

**Comment by vassbo** [comment]
It didn't work. But I think I know the issue, hopefully it works in the next version!

**Comment by vassbo** [comment]
This should now work!
