### ISSUE TITLE
Bulk Apply Template to Slides

### ISSUE THREAD

**Issue by Dcanadian** [vassbo/freeshow#1037]
**Describe the feature**
My church's setup uses slide templates a lot - it's a great feature. However, we haven't been able to apply a template across all the individual shows in our library, so often the display of the slides in the "show" tab is badly formatted by default. (See below screenshot) 

We have our outputs set to style the slide text to override with a certain template, but it would be nice to apply templates to the thumbnails in the slide viewer. It would be nice to manually assign the template to all the shows by mass selecting, but I'm not able to do that in the current version

Could we make possible to style all the songs in a category (e.g. "Hymnal") to both display output with the same template?

**Additional context**
Notice that, even though the outputs show a formatted version of the song text, the preview does not, thus making it hard to know the contents of each slide at a glance.
![image](https://github.com/user-attachments/assets/816e52b0-0c73-4111-94de-199bdf69f879)

**Comment by mwb9aa** [comment]
If my memory is correct, my installation seems to take the settings from the template labeled "Default" from the template drawer and the category (song, scripture, presentation, etc.) that matches the label of the show. If that is true, then perhaps editing the Default template to match your needs would help?

**Comment by mwb9aa** [comment]
@Dcanadian
I had a similar issue a few versions ago with a template not "applying" to an output. I ended up coping my configuration files and starting FreeShow as if for the first time. I then added each one of the files back one by one. (I would close FreeShow, copy a file, and open FreeShow to see if the changes I expected occurred.) The history.json file is the one that caused the problem. Maybe one of your config files was corrupted somehow?

**Comment by vassbo** [comment]
@Dcanadian I'm pretty sure you have the "Header" template applied to all your shows, so editing that will fix the style in all of your shows!

As we have the "Category action" now, all I would need to do it create a new action to change template on selected show.
Maybe also a "Activate when show is opened" trigger.

**Comment by vassbo** [comment]
All right!

Creating an action is as simple as going to "Functions">"Actions", clicking "Add" and choose the desired action.
I have not yet added an action to template.

I hope to get some more helpful screenshots/videos out sometime soon, when there is time.
