### ISSUE TITLE
Make the output screen bigger

### ISSUE THREAD

**Issue by AngangGuo** [vassbo/freeshow#1059]
**Describe the feature**
When there're two output screens, each one is showed out and the size is very small.
Is it possible to show only one screen at a time so that the size can be bigger? 
Maybe like ProPresenter which uses a dropdown menu to select which one to show out. (See sample picture below)

**Additional context**

![image](https://github.com/user-attachments/assets/ee1a6052-a1d8-47e4-8114-7b4add80d742)

![image](https://github.com/user-attachments/assets/945e6e7c-ecaa-4e56-be5c-2c66abc84f1d)

![image](https://github.com/user-attachments/assets/8f6aecb5-143f-4f8d-8dd4-4f147b1a473f)

**Comment by vassbo** [comment]
Yep, right click the output you want to hide:
![image](https://github.com/user-attachments/assets/e348b252-4ca2-460e-96bf-83c86102c6ae)
