### ISSUE TITLE
OpenLP importer lines

### ISSUE THREAD

**Issue by odlg** [vassbo/freeshow#108]
It seems that importing from OpenLP makes only one slides/xxxx/items/lines/text/value for each verse. The lines in the verse are separated by \n.
Making shows manually makes one line in a verse pr slides/xxxx/items/lines/text/value
Formatting and editing OpenLP imported songs are hard. The entire verse is one line basically.

**Comment by vassbo** [comment]
Hi, I would like to fix this. 😊 Could you send over some of the song files from OpenLP? So I can take a look.

**Comment by odlg** [comment]
I have sent a couple of songs by email.
