### ISSUE TITLE
VideoPsalm Large Songbook Import Issue

### ISSUE THREAD

**Issue by muffay** [vassbo/freeshow#109]
I'm having issues importing videopsalm songbook.

I would go to File > Import click on VideoPsalm Icon, then it opens the videospalm songbook folder. When I click on the main songbook file nothing happens. If I try importing the smaller songbooks with less than 10 songs it works fine, but the larger songbook with over 600 songs does not import. The files are save in ".json"

Am I missing something?

System Specs:
OS: Windows 7
CPU: Intel i3
VideoPsalm 1.23

**Comment by vassbo** [comment]
Sent you a mail. 😉

**Comment by muffay** [comment]
My VideoPsalm library import is working!!! Thank you.
![Import Success](https://user-images.githubusercontent.com/127272066/226223057-cdccc67a-8501-4dfe-b40a-78a0af088f46.jpg)
