### ISSUE TITLE
snap version menus empty

### ISSUE THREAD

**Issue by odlg** [vassbo/freeshow#110]
Using the snap version of 0.7.1 menus are often empty. 
![Screenshot from 2023-03-10 21-18-43](https://user-images.githubusercontent.com/2950255/224421373-d2ea9b61-4449-4008-bd33-e036e663242d.png)
After traversing the menus for a few seconds FreeShow freezes and some seconds later this is shown:
![Screenshot from 2023-03-10 21-20-33](https://user-images.githubusercontent.com/2950255/224421503-cd6f0d8d-ea1c-4562-8faf-c207c41106a7.png)
I am on OpenSUSE Tumbleweed. Using the AppImage version does not show the same problems.

**Comment by vassbo** [comment]
Thanks.

This is a problem with electron and the specific software/hardware, and is not something I can do anything about.
Here is a discussion I found of the same issue: https://forum.snapcraft.io/t/empty-dropdown-menus/29392

Looks like this might be a temporary fix: https://forum.snapcraft.io/t/empty-dropdown-menus/29392/21
