### ISSUE TITLE
add new function: Display two Bible 

### ISSUE THREAD

**Issue by paulnatemv** [vassbo/freeshow#112]
Can we please add function to display two bibles, for example English and Spanish same time https://prnt.sc/yO5FCcbMkjsn

**Comment by vassbo** [comment]
Yes. That would be nice! 😊
It's on the todo-list, so hopefully it will be added soon.

**Comment by paulnatemv** [comment]
When will be available on Mac? ---- On Sun, 19 Mar 2023 13:43:34 -0500  ***@***.******@***.***> wrote ----  
Closed #112 as completed.

**Comment by vassbo** [comment]
@paulnatemv It is available in the latest version. Go to freeshow.app to download. 😄

**Comment by vassbo** [comment]
Here is a small guide: [Create a collection](https://freeshow.app/docs/scripture#create-a-collection)
