### ISSUE TITLE
Export multipe/all shows?

### ISSUE THREAD

**Issue by odlg** [vassbo/freeshow#121]
On linux in 0.7.2 I am unable to select multiple (or all) shows in the list in the bottom and export them. The export window says it can export 'Selected shows' - but I am only able to export them one at a time. Am I overlooking something? :-)

**Comment by vassbo** [comment]
Hi, you can hold left click down and drag, or hold CTRL while clicking on the shows to select multiple. 😊
But I guess I can add an option to export "All shows".
