### ISSUE TITLE
Use Timer in Overlay, global timer, slide groups 

### ISSUE THREAD

**Issue by FelixHeppner** [vassbo/freeshow#122]
The program looks very promising already. Thank you for your effort!

I am not sure whether these are bugs or just user (my) errors. Any hints are welcome.

1.) I added an timer to an overlay. But I cannot find a place to start the timer. The use case is to display a timer over a pre service slide show with announcements. 

2.) Can I use the global timer (count down to time especially) in an overlay as well? I can only see the option for stage display.

3.) Is this group thing for lyric slides "only" a color thing? A typical verse will split out to three or four slides Named "Vers", "Vers 2", "Vers 3" etc. when I want to add the verse after the chorus again I have to add the four slides individually although it make no sense most of the time adding half the verse only. So a logical grouping would be nice? Or perhaps it is there but I don't get the  user interface.

BTW: we are currently using quelea projection. That works quite okay, simple an robust but stage display options are quite limited in that NO graphics are displayed there.  I am still working out the possibilities for FreeShow.

**Comment by vassbo** [comment]
Thank you so much.

1. I have not implemented this yet, but will very soon.
2. Not yet, but soon.
3. No, groups are for different verses. If it's the same verse it should be just a parent "Vers" with multiple children slides in the same group. Clicking "Add slide" in edit should make it a child automatically. But if you select all the different grouped slides you have, right click, then "Change group", then click "Verse". They should all be merged into one group.

Just let me know if there is anything else. 😄

**Comment by FelixHeppner** [comment]
Thanks for the info on timers.

I had a hard time reproducing the behavior you describe but it finally works. 

Using "New Slide" in edit mode (the labeled + Button under the list of slides) selects the next slide or the first one when the last has been selected and does not add a slide at all. At least not for a song imported from clipboard. When I manually create an empty show the add button works and it works as you expect by adding a new slide in the existing group.

I can use "duplicate" in edit mode though and that is actually what I would normally do to "split" one slide with too many lines to two or more. The duplicate slide is at the end of the list as mentioned in #115. Reordering the slides only works in show mode in the center pane, not in the list in edit!? Whatever, it works at least in show. 

The hard thing is to select the slides to be grouped in one group. The currently edited slide (displayed in center pane) is not selected by default. When I ctrl+click the second slide I have to ctrl+click the first slide again to make them both "selected". The visual feedback is subtle but there, the selected slides get a greyish overlay. 

It is not possible to "deselect" everything after one slide has been selected once with ctrl+click. Changing to show and back to edit again removes the selection (and selection indication) from all slides.

We all love focus and selection tracking ;-)
Are you interested in pull requests? I can't really promise anything soon, my typescript skill might be improvable and I never worked with svelte, but it's just software after all. 

Should I open a separate issues for  "slide selection handling in edit mode", "reorder slides in edit mode" and the "new slide in edit mode does not always add a slide"? 

And one last thing:  for me the delete key is the expected way to delete selected items. In free show there are at least a couple of places where only backspace (mac style?) works and there is now content menu for workaround. I had a look in the code to find how do delete elements in the stage editor. Is this "backspace only" intentionally or any chance to bind delete key as well? Or make it configurable?

This could have been a discussion not an issue. Sorry. I saw too late that you have discussions as well and you do link to issues only on the github main page.

**Comment by vassbo** [comment]
This was a lot, but thank you. 😊 I will just keep this issue open until it's done.

- If you want to split a slide in two, just hold the ALT key and press enter with the text cursor anywhere in the text, and it should split it.
- Will look at the reordering in edit mode.
- I will fix the CTRL+click selection issue.
- I will make the selection more visible, good feedback.
- You can deselect everything by just clicking anywhere else in the application. But will change it so you can deselect it by clicking on the last selected slide too.
- I have actually made it so both Backspace and Delete key do the same thing most of the time, but I guess I have missed some areas.

I am very interested in getting pull requests. I can fix these issues pretty easily I guess, but if you want to make some improvements, they are always welcome.
