### ISSUE TITLE
importing files bug

### ISSUE THREAD

**Issue by gonzodj** [vassbo/freeshow#128]
Dear FreeShow developer,

Congratulations, i love your app, i was testing from the first version.

This time i was trying to import some Bible, but the program frezze like show the video.

[https://drive.google.com/file/d/1bwZFozlRO051pvLajao2nWlvyEfMYksg/view?usp=sharing](url)

Best whises.

**Comment by vassbo** [comment]
That's awesome! Thank you so much. 😁

I will see if I can fix this for the next version. 😊
