### ISSUE TITLE
New Slide Creation Issue (v0.8.0)

### ISSUE THREAD

**Issue by ITMan101** [vassbo/freeshow#130]
### Cycle Bug
In the first gif, on clean startup of FreeShow I open a show go to the "Edit" tab and the "New Slide" button in the left-hand bar works as expected. However, once I go back to the "Show" tab and select a slide, coming back to the "Edit" tab causes the "New Slide" button to cycle through the slides instead of creating a new slide.

![NewSlideCycleBug](https://user-images.githubusercontent.com/16481671/233106398-51619422-b76d-4050-9273-b81613383daf.gif)

### New Slide on Show Tab
When using the pop-up menu to create a new slide on the "Show" tab it works as expected until you select a slide and then it ceases to create new slides.

![NewSlideSelectionBug](https://user-images.githubusercontent.com/16481671/233106404-e0bb36f4-cc59-4a7f-94b4-a153af971580.gif)

### Additional Note
Something else I noticed which can also be seen in the second gif is that the pop-up menu for creating a new slide on the "Show" tab only appears when right-clicking close to other already present slides. How I would expect this to work is that the menu would be available when right-clicking anywhere within that center panel on this tab.

**Comment by vassbo** [comment]
Thanks, I'll take a look.
