### ISSUE TITLE
Stage Output

### ISSUE THREAD

**Issue by ITMan101** [vassbo/freeshow#131]
I noticed currently stage outputs can only be connected through the web service. It would be nice if they could also be a physical output in the outputs settings menu.

**Comment by vassbo** [comment]
Currently on the TODO list. 👍

**Comment by ITMan101** [comment]
Not sure if this is on the TODO list as well, but being able to use a Chromecast as an output for Stage or Audience could also be useful.

**Comment by vassbo** [comment]
Good idea. I'll think about it, it depends on the difficulty of implementing it.
