### ISSUE TITLE
Slide Themeing Rehaul/Addition of "Styles"

### ISSUE THREAD

**Issue by ITMan101** [vassbo/freeshow#132]
### Current

- Only one template can be applied to a show at a time.
- You can only set up one template override for an output overall.
- You can only set the active layers per output overall.

### Proposal

- Allow templates to be set per slide or per group, this will especially help with presentation creation where each slide is often different from the last.
- Remove the template override and active layers options from the outputs settings menu and give them their own menu (i.e "Styles")
- Allow "Styles" presets to be created with template overrides and layer options per output.
- Allow this "Style" to be changed using a slide action.

**This suggestion is based on the feature present in ProPresenter called "Looks."**

_Screenshot of the "Looks" menu from ProPresenter_
![image](https://user-images.githubusercontent.com/16481671/233115293-5d0a6452-7b9e-4714-bca2-1a2f62d70012.png)

**Comment by vassbo** [comment]
Hmm... I'll think about how to do this in a good way,

**Comment by ITMan101** [comment]
I noticed you added styles but there is still no way to set the active layers and override template for each output. This change also doesn't seem to extend past the slide with the action. Maybe I do not understand how this has been implemented.

**Comment by vassbo** [comment]
I'm not sure I understand what you mean.

You can create different styles where you can change the different layers and override the output with a template. The styles can be applied manually to a output, be set with MIDI input action, or from a slide action, meaning you can change the active output style (layers/template) for a given output by clicking on a slide with that action!

To apply different styles for different outputs without doing it manually, you would currently have to activate just the one output where you want to change the style, and activate the change style action.

**Comment by ITMan101** [comment]
Sorry, life got hectic. It's your last statement where I think we differ:

> To apply different styles for different outputs without doing it manually, you would currently have to activate just the one output where you want to change the style, and activate the change style action.

The ability to change the template on multiple active outputs simultaneously. This is especially useful when live streaming because you can use the same content and have it displayed differently depending on how you are wanting to present it to both audiences. 

**Example**
You could create a style template for each of these scenarios and activate them with slide actions.
- Song Words - (FOH) Centered, Background, (Live Stream) Lower Thirds, No Background
- Image/Video - (FOH) Fullscreen, (Live Stream) Full Screen


If you look at my original post, in the image there is a bar on the right which lists all of the user creatable "look" presets. These can be activated by a slide action.
In the main panel of the UI it has strips for each of the outputs. This strip lets you set which layers are active and set an override template for each output.

Hope that describes better what I was trying to originally say.

**Comment by ITMan101** [comment]
If this could be carried out within the styles menu it would save a lot of clicks when you need to switch back and forth. The style saves a lot of time in scenarios where you have many different outputs with many different templates. I don't remember if this is the case but styles should persist past the slide it's changed on.

**Comment by vassbo** [comment]
In the latest update I made it so you can choose specific outputs and individual styles, from the slide action "Change output style". The style will persist on the output until it's changed again.
I figured the best way to set the styles manually, was to choose a style for each output as it was previously, that way you can easily manage both styles and outputs. 😊
