### ISSUE TITLE
Freezing on Scripture Tab

### ISSUE THREAD

**Issue by yookzz** [vassbo/freeshow#133]
I recently download v0.8.0 and anytime I click on the Scripture tab, the program freezes and I can’t move to any other tab again. I am also forced to force quit the app since quitting does not work.

**Comment by vassbo** [comment]
Hmm... I can't seem to replecate the issue. But I'll try my best to fix it. Did you have any scriptures imported?

**Comment by yookzz** [comment]
I do not know how to import a scripture yet. The video I’ve attached shows the issue I’m facing. 

https://user-images.githubusercontent.com/57093338/233852304-2018303f-efa7-400c-9faf-68ab3abba469.MOV

**Comment by vassbo** [comment]
Hi, could you update to the latest version and check if it works now?

**Comment by yookzz** [comment]
I’ve updated it but unfortunately I still have the issue.

**Comment by vassbo** [comment]
Okay. Are you able to find the settings.json file in the programs data folder and send it over?

**Comment by yookzz** [comment]
This is it. 
[settings.zip](https://github.com/vassbo/freeshow/files/11304913/settings.zip)

**Comment by JacobAkers** [comment]
This is my output from freeshow when launching from terminal. Not sure if it will help or not but thought it couldn't hurt.
![freeshow_cli_warnings](https://user-images.githubusercontent.com/7428689/234446688-847ecdb0-79c3-46fd-a456-c0be7e962481.png)

**Comment by vassbo** [comment]
Thanks. It doesn't show this error. But I see another error in this console, that I can fix, but I don't think is an issue.

**Comment by JacobAkers** [comment]
I downloaded Freeshow-0.7.2.AppImage from github and ran it and the scripture tab works fine.  I'll tinker around with it and see if it will meet my needs for the time being.  I'll keep checking back on this fix though.  Thank you for your efforts on this project, when I have some extra cash I'll contribute.

**Comment by vassbo** [comment]
Thank you. I think I have fixed the issue for the next version. It should come out this weekend. 😊

**Comment by vassbo** [comment]
This issue should be fixed in the latest version. Can someone confirm that it works?

**Comment by yookzz** [comment]
Yes it works now. Thanks a lot!
