### ISSUE TITLE
All app froze after using "Player" Tab

### ISSUE THREAD

**Issue by athanray** [vassbo/freeshow#135]
I am using FreeShow version 0.8.1 in Windows 11, which as my testing so far is less buggy than 0.7.2 and 0.8.0. But there is one problem that can be frustrating which is when I click on the Player tab and choose the default YouTube video (The Chosen Trailer), the video played fine, but all of the apps will freeze, and I can't click anything (even clicking the close button, have to use task manager). 

 I attached a video below.

https://user-images.githubusercontent.com/131677652/234006923-d52af894-87b3-4adc-9eb5-b9f44b74b0a4.mp4

Keep up the good work! This is, as far as I know, the only free app that can output to multiple displays. I also still waiting for NDI support (though I understand it's complicated). Thank you!

Also, is there a way to edit existing songs with Quick Lyric? Similar to Reflow in ProPresenter and when I create a new song in this app.

**Comment by vassbo** [comment]
Thank you! It looks like the app freezed when you clicked on the "Scripture" tab. Which is the same issue as this: https://github.com/vassbo/freeshow/issues/133
I will hopefully get this fixed for the next version! 😊

Yes! If you click or right click on this button you can change to "reflow", lyrics or a plain text editor.
![image](https://user-images.githubusercontent.com/17619496/234043327-de5ca552-6287-4d74-9fe7-f1aa654217bc.png)
