### ISSUE TITLE
Feature Request: Recording to mp4

### ISSUE THREAD

**Issue by 7flash** [vassbo/freeshow#138]

**Comment by vassbo** [comment]
Sounds interesting... Could you explain a bit more how you would like this to work.

**Comment by vassbo** [comment]
Okay. I'll see what I can do, depends on how easy it is to implement.

**Comment by vassbo** [comment]
You can now record screens by goind to the "Live" drawer tab, right clicking a window or screen and choose "Start recording"! 😊
