### ISSUE TITLE
low resolution thumbnails in "Show" or "Edit" view

### ISSUE THREAD

**Issue by gewa43jh65j5kqe43** [vassbo/freeshow#141]
I like to use Freeshow, but I have the problem, that I can't read any of our sermon slides in the "Show" view (We don't build them with Freeshow; We use Photoshop and import them as pictures to Freeshow). The Resolution of a single slide is maybe 144p or less, even if I zoom to 33% or 50% on my 4k monitor. The slides are shown in full resolution in the preview or on my outputs.

Thanks for Freeshow, it's a great free alternative to Propresenter
![Screenshot 2023-05-06 115148](https://user-images.githubusercontent.com/69010702/236617549-83bc1831-f1bc-485e-98ba-c0b67d04901e.png)

**Comment by vassbo** [comment]
I'll look into a way to make this better.
