### ISSUE TITLE
Multi-screen mismatch

### ISSUE THREAD

**Issue by Belongshere** [vassbo/freeshow#142]
First of all, thank you for this promising approach of FreeShow.
I noticed the following bug in version 0.8.2:
A) The numbering order of FreeShow does not match the order under Windows 10.
B) The selection dialog is cropped.
![grafik](https://github.com/vassbo/freeshow/assets/133128856/f7a092d5-ec6d-4a20-9794-3542fc7e81e7)

I made the above observations on three different screen setups on three different PCs/laptops.

**Comment by vassbo** [comment]
Thanks. I'll take see what I can do about it!
