### ISSUE TITLE
Retain Slide Notes formatting on Stage Displays

### ISSUE THREAD

**Issue by abbasou** [vassbo/freeshow#143]
Would love to see improved formatting options for the slide Notes field, or at the very least would love for it to retain formatting.

Currently when displaying Slide Notes on a stage display, line breaks, extra spaces, etc. are evidently removed and text is reduced to all one wrapped line.
![image](https://github.com/vassbo/freeshow/assets/68356554/1df29c04-b515-413a-becb-058f8fa110d6)
![image](https://github.com/vassbo/freeshow/assets/68356554/409c97be-57c7-4255-8911-61b834e73442)

Upon examining the .show file, it's evident it's basically a CSS formatted document and all the spaces and lines breaks were present, so it seems more related to how notes are displayed on the stage screen.

**Comment by vassbo** [comment]
I can correct it so the line breaks are showing in stage.
But I think it's better to add chords in edit, on top of the existing text, and enable it in stage (at least when I have enhanced it to work better).

**Comment by abbasou** [comment]
Sorry, I'm not sure I understand. How do I add chords over top and enable only on Stage?
Also, I have many chord sheet documents already, so being able to just paste in would be a great convenience for importing my library. Are you say there is a way to add a text box, but only make it visible on Stage? This is currently how I use Slide Notes (in ProPresenter).

**Comment by vassbo** [comment]
In the "Edit" tab in the bottom you can see a button with a note icon, click on it to activate chords mode. Then all of the textboxes will have a "+" icon in the top right. Click on it to add chords.

Then in the "Stage" tab, select the textbox and enable the checkox on the right where it says "Chords".

Currently it's not fully implemented, so you might be better of doing what you do now.
Soon I will have support for the ChordPro format meaning you should be able to easily import the text and automatically add chords. 😊

**Comment by abbasou** [comment]
So I tried the current iteration of Chords, but it does seem pretty broken. For my particular use case, simply retaining Notes formatting (with the future enhancement of doing some minor formatting *in the notes field* in Edit) would basically solve my problems with songs and go a long way toward FreeShow becoming a viable replacement for ProPresenter for us. I need to better understand templates and stuff to determine if using a Stage Display or some other output can effectively replace our NDI output for our current setup.
