### ISSUE TITLE
UI freezes on many different actions

### ISSUE THREAD

**Issue by macdelacruz** [vassbo/freeshow#151]
Deleting a new custom template doesn’t work. I tried to delete a template I created, but the UI freezes. I'll need to force close the app from the task manager in Windows 10. There are many instances when the UI freezes.

I'm using the latest release 0.8.3.

**Comment by vassbo** [comment]
Hi, thanks. I have fixed this in the dev version, and it will work fine in the next update. This also affected deleting overlays.
Please let me know if you know any other ways the program freezes!

**Comment by macdelacruz** [comment]
Thanks Kristoffer. I was able to test the dev using `npm install` and then `npm start. The first run is great, but I can't seem to run it again as I get stuck on the splash screen. Is there an additional step I'm missing?

**Comment by vassbo** [comment]
You are doing it correct. I don't know why it doesn't work. 🤔
If you don't get any errors in the console, try increasing the dev timeout value in index.ts line 32 from 15000 to e.g. 20000.

**Comment by OnceI** [comment]
Hey,
I think I found a bug related to this topic. I tried to change the transition for current slide on the right under Layout. The popup shows as expected but when selecting a transition the UI freezes. And I'll need to force close the app from the task manager. 

Also, if i select Live -> Cameras (Don´t have any camera) the UI freezes too.

Windows 10. Freeshow release v0.8.4
