### ISSUE TITLE
linux is NOT supported

### ISSUE THREAD

**Issue by thebiblelover7** [vassbo/freeshow#16]
Why does this error message appear? Why do you publish linux .AppImage if it is not supported?

**Comment by vassbo** [comment]
Hey, sorry about that. Haven't tested it on Linux in while. This version works on Linux (Double click to remove black screen after opening program): https://github.com/vassbo/freeshow/releases/tag/v0.1.1

I will look into it, it's probably a npm package that's not supported. :)

**Comment by thebiblelover7** [comment]
> Hey, sorry about that. Haven't tested it on Linux in while. This version works on Linux (Double click to remove black screen after opening program): https://github.com/vassbo/freeshow/releases/tag/v0.1.1
> 
> I will look into it, it's probably a npm package that's not supported. :)

Well, on v0.2.1, it doesn't even show a black screen. It exits out immediately. That error message only appears when I run it on the terminal.

Also, is this Electron based?

I'm on wayland too.

**Comment by thebiblelover7** [comment]
Ah wait, I get it, version 0.1.1 works on Linux

**Comment by vassbo** [comment]
The issue was a package called "pdf-poppler". Used to export as PDF. Will just disable PDF exports on linux for now, and update the program in the next days.

**Comment by thebiblelover7** [comment]
If you want, I can help test it out and help fix this

**Comment by vassbo** [comment]
Thank you, but I have already fixed it (Used Kali Linux in VirtualBox to troubleshoot).
I will just add some more features, then push a new release. ;)
But if you find any more bugs on Linux (which I don't test very often, you can report them here).
Or fork this project and help in coding if you want. :)

**Comment by thebiblelover7** [comment]
@vassbo Perfect! Excited to try this out, it looks like some great work you've done!

**Comment by thebiblelover7** [comment]
@vassbo Just built it manually and it works! It's pretty cool!
