### ISSUE TITLE
Not choosing background image freezes the app

### ISSUE THREAD

**Issue by lubomsky** [vassbo/freeshow#161]
Only restart helps.

**Steps to reproduce:**
1. Go to settings
2. Go to styles
3. Click on "Choose media" button next to "Background image"
4. Click cancel on file selection window

_Linked enhancement to this topic: clicking on a previously added image removes it, maybe add some info about that option?_

**Comment by vassbo** [comment]
Thanks! I fixed this. I also added a new remove button to remove confusion.
