### ISSUE TITLE
Broken Textbox after removing last character

### ISSUE THREAD

**Issue by lubomsky** [vassbo/freeshow#162]
Only deleting broken textbox and adding new one helps.

**Steps to reproduce:**
1. Go to some show
2. Go to edit slide
3. Create new slide with textbox or edit existing one (with textbox)
4. Click backspace on new slide or delete all characters on existing one
5. Type something again

**Result:**
Slide won't save and preview will look like this
<img width="908" alt="broken texbox" src="https://github.com/vassbo/freeshow/assets/87763712/5007ed10-f147-4879-8fe3-72ae4c28d64a">

**Comment by vassbo** [comment]
I will look into this. Thanks!

**Comment by vassbo** [comment]
This is fixed, as well as a few other simular issues. Like not being able to have empty lines! 😊
