### ISSUE TITLE
Closing media preview

### ISSUE THREAD

**Issue by lubomsky** [vassbo/freeshow#167]
What do you think about additional button for closing media preview? Maybe a bar under the preview with "close preview"?
In my opinion rightclick and close is not the first choice, and ESC button clears the output 😊

**Comment by vassbo** [comment]
Thanks for the suggestion. 😄 Maybe, but I don't think it would be neccesary in the latest update, as currently to open the preview you have to either right click a media preview in the drawer, or open it from a project. And when you open it from a project you don't need to close it.

Btw, the "Close" button is actually a "Change back to the last opened show" button. It's a good suggestion, but I don't want to have unnecessary buttons if there no good need for them.
