### ISSUE TITLE
Draw window stays on images

### ISSUE THREAD

**Issue by lubomsky** [vassbo/freeshow#168]
Tried on mac and windows.

**Steps to reproduce:**
1. Open some show (problem does not occur on welcome screen)
2. Toggle media (picture)
3. Go to Draw
4. Go to Show

This is happening only with images and in transition from Draw to Show.
To remove that issue it's necessary to:
1. Go back to Draw
2. Go to Stage, Calendar, Edit or Settings
3. Repeat 1 and 2 if didn't help

And then it's ok, unless you go back to Draw and Show again.

<img width="1680" alt="<on presenting picture> Draw -> Show bug" src="https://github.com/vassbo/freeshow/assets/87763712/ef9215fc-567c-460a-94eb-9aa1ae94550f">
<img width="1680" alt="<on presenting picture> Draw -> Show bug another example" src="https://github.com/vassbo/freeshow/assets/87763712/9dee3134-4ee3-4759-96cf-2bcdf1697d05">

**Comment by vassbo** [comment]
Right, thanks! This is a bug due to the way Svelte handles transitions, but I fixed it by disabling transitions in the draw page.
I have fixed this for videos, but it looks like I didn't do it for images. 😊

**Comment by lubomsky** [comment]
Cool that you have ready-to-go solution 😊

**Comment by lubomsky** [comment]
Player for Vimeo and YouTube also behave that way 😢 

Additionally on Mac: 
- Vimeo can run audio again when you move between Show, Edit, Calendar, Draw and Stage. 
Maybe it is connected to the Svelte transitions?
- The output preview on YouTube is loading forever or loads with delay, but output is working just fine.


_Maybe it's for a different topic - but how do you feel about YouTube and Vimeo preview?
After changing preview to a rightclick menu on media and toggle play by single click, I wish to have that also on this Player section._

**Comment by vassbo** [comment]
Thanks. I will fix the issue.

_Good point! I guess that would be nice, maybe also audio too. 😊_
