### ISSUE TITLE
Feature suggestion: Auto save or auto recovery

### ISSUE THREAD

**Issue by macdelacruz** [vassbo/freeshow#170]
Hi. I have been an avid follower of this project and really appreciate your dedication in developing this actively and offering it free and open source. 

Power outages are inevitable. So I think it should be possible to automatically save changes or be able to recover edits when the program is suddenly shut down.

**Comment by vassbo** [comment]
Thank you! Good suggestion. 😊

**Comment by lubomsky** [comment]
+ what about removing .show file from Shows folder by default?
Is there any reason to delete shows only from the UI, and reload or delete shows that are not indexed on demand?

**Comment by vassbo** [comment]
I can add a bit more description to what these buttons do.

It's basically because when you delete a show file it doesn't get deleted in the Shows folder. Also there might be some issues with not all files loading, so you can reread the folder to fix these issues. So in most cases there is no need to use these, but might come in handy.

**Comment by lubomsky** [comment]
Maybe I didn't write clearly.

I am just wondering, why the show is not deleting from the Shows folder automatically. To do it, user have to go to settings, others and click "delete shows...that are not indexed"

For example media and pictures are loading from their path each time you open the folder. Shows behave differently.

**Comment by vassbo** [comment]
The list of all shows are stored in a single file for faster loading. That's the way it has been done. The files should be deleted when the show is deleted, but I haven't implemented that yet, mostly for a user to be able to undo a deleted show, but I will probably change this sometime. Hope this makes sense.
