### ISSUE TITLE
RemoteShow scrolls up when clicking on slide

### ISSUE THREAD

**Issue by macdelacruz** [vassbo/freeshow#171]
On v. 0.9.0 please open RemoteShow on browser. When you click on a slide, the page scrolls up automatically and the selected slide is not centered on the viewport.

[RemoteShow.webm](https://github.com/vassbo/freeshow/assets/13848476/5efe13ef-22da-4224-991c-7af65d4276f5)

**Comment by vassbo** [comment]
That's because it's made for smaller screens (mostly phones), but I'll see if I can change this behaviour!
