### ISSUE TITLE
Local Media Files Do Not Load - Linux

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#172]
Holy cow, 0.9 is looking amazing!

I was playing around with the new features today, and I noticed that when I link local folders in the Media bin, they just show the "loading" animation and never actually load in. Other sources like Pixabay still work fine, but pictures and videos on my machine do not.

**Comment by vassbo** [comment]
Hmm... I'll investigate. It's working fine on Mac and Windows.

**Comment by jdcarls2** [comment]
For the record, I was running it via the repo, not the release from the website, so let me check and see if that was part of it.

**Comment by jdcarls2** [comment]
Okay, my mistake. Works *perfectly* in the AppImage for Linux.

When I run it via `npm start`, is there a reason it wouldn't be able to access local media files?

**Comment by vassbo** [comment]
Okay, great! I don't know why it doesn't work via npm start. Have it worked in previous commits? The difference is that "npm start" runs in a local webserver, so maybe it don't have the right permissions to access the files.
