### ISSUE TITLE
Toggle slide behaviour 

### ISSUE THREAD

**Issue by lubomsky** [vassbo/freeshow#174]
I'm coming with another idea.

Sometimes during the presentation, there is a need to quick edit a slide content, like a typo.
In the app we have few options:
- Switch to Edit module, 
- List view,
- Text edit (another view),

and it's very cool.
After the change, it is instinctive to click the slide again to push a corrected slide to the output.

What do you think?

_By the way. The List view has a right section to edit content. When the slide is empty, the first idea is to click there and type. But the cursor changes and allows you to click a bit further past "Type something". When the slide has the content, the whole right section is clickable._

**Comment by vassbo** [comment]
Yes, you can update the output slide by clicking on the slide again or pressing the refresh button under the preview. In most cases you don't edit while presenting, but in the cases you do, like to fix a typo or change some things it's much better for the audience to just see a one time update of the changed slide, because it's distracting to follow along while the content is changing constantly, so I think this is the best way.

_I'll see if I can fix the list view issue._

**Comment by lubomsky** [comment]
Alright, so there should be an option to kind of refresh the output by clicking on the slide again?
I tried it on mac and windows, and in fact, the refresh button works like it should (I forgot about it...), but clicking on active slide is ignored.

**Comment by vassbo** [comment]
No, you **can** click on the slide to update it! I don't see the issue.

**Comment by lubomsky** [comment]
Maybe I can't explain it in writing:

https://github.com/vassbo/freeshow/assets/87763712/5fc40c60-0e32-4b94-a464-fc06dc9345bb

**Comment by vassbo** [comment]
I did this exact same thing and it's working just fine for me, so I have no idea why it doesn't work for you.

**Comment by vassbo** [comment]
Looks like an issue on macOS only. I don't know why. 🤷‍♂️

**Comment by lubomsky** [comment]
Yes, pretty interesting 😃 
Btw. I have downloaded 0.9.1 for windows and it behaves the same way, but on the second windows laptop it works fine (but I can test it only on dev env from ide/terminal).

I doubt it has any priority... There is an update button, and even shortcut 😊 
Maybe close for now?

**Comment by vassbo** [comment]
Interesting. Thank you!
Just let me know if you find out anything more. 😊
