### ISSUE TITLE
Suggestion: Predefined colors on color picker

### ISSUE THREAD

**Issue by macdelacruz** [vassbo/freeshow#179]
I think it's easier to use the color picker if there is, sort of, a set of predefined colors on the color picker. I'm trying to change the color of my custom groups but if I have so many of them, I need to manually input RGB/HEX code if I want to reuse the same color.

![color-picker](https://github.com/vassbo/freeshow/assets/13848476/b7380914-233e-499b-8580-d842d064e065)

I suggest putting a standard color palette on the color picker (something like the color picker of MS Word). Or maybe much simpler, just a dropdown of red, green, blue, yellow, white, black, etc.

![color-picker2](https://github.com/vassbo/freeshow/assets/13848476/414356c8-e62f-439c-ae69-95a8dbf1be82)

**Comment by vassbo** [comment]
Good suggestion! I wish the Chrome webpicker had that by default, like the macOS one, but I guess I can add my own. 😊

**Comment by macdelacruz** [comment]
Wow. That was implemented real quick. Kudos to you! :raised_hands:
