### ISSUE TITLE
Format tool not working on template editor

### ISSUE THREAD

**Issue by macdelacruz** [vassbo/freeshow#180]
On v.0.9.0 edit a template, right click on text item, select Format > Make uppercase (or other options), nothing happens on the text. My workaround is to manually type `text-transform: uppercase;` on the CSS textbox.

![format-not-working](https://github.com/vassbo/freeshow/assets/13848476/35842aba-bec2-4999-9106-b993de66441e)

**Comment by lubomsky** [comment]
The format generally works, but the change is not visible on the current textbox/slide without switching tab or slide (if you are editing show).

**Comment by lubomsky** [comment]
It looks like these buttons are not active. If pressed, nothing happens (the menu should hide).

I thinks the template editor do not behave like slide editor. For example if you duplicate textbox on "big bold" and try to delete, it just resets it's position.

More critical: try to duplicate textbox on the template with more textboxes (like these for the scripture), the app freezes.

**Comment by vassbo** [comment]
I'll see what I can do.

**Comment by macdelacruz** [comment]
Now on v.0.9.1. Format tool works in the templates editor now, but changes won't apply to the show.

https://github.com/vassbo/freeshow/assets/13848476/286c0c3d-faf5-48a4-96ef-95d7e2edabc5

**Comment by vassbo** [comment]
The format tool changes just the current text. But I guess add a text-transform style option.
You can currently select all the slides in the show, and format them all in one go.

**Comment by macdelacruz** [comment]
Yes I can do that, but I like the idea that I can quickly switch templates. The template should override the formatting set on all Slides _every time_ it is selected.  I think, how the template is styled, how it looks, it is that should always apply to all slides, overriding whatever formatting, font, style, alignment etc. that is done at the slide level.

**Comment by vassbo** [comment]
Agreed. I'll probably add a dropdown to change the text-transform css property.
