### ISSUE TITLE
Feature request: search or filter on shows, scripture, etc.

### ISSUE THREAD

**Issue by macdelacruz** [vassbo/freeshow#184]
Eventually you'll have a growing list of shows, songs, media, audio etc. that you'll reuse in every event, so I think a search box on them is going to be very helpful. Also in Scripture, I suggest adding a search box or filter to quickly find a book, chapter, verse.

**Comment by vassbo** [comment]
There already is! 😉

![image](https://github.com/vassbo/freeshow/assets/17619496/8fc7833a-4b78-460b-b688-83acd86a9131)

**Comment by macdelacruz** [comment]
Oh I did not easily find that. I see now that there is a magnifying glass icon on the rightmost of the Shows/Media/Overlays tabs row. I'd suggest just have the search input always visible instead of the need to click on that little magnifying glass icon.

**Comment by vassbo** [comment]
I added the magnifying glass in the latest version (0.9.2) to make it easier to find! (And make more space for the tabs on small screens)
I think it's better to have it there.
