### ISSUE TITLE
Media on Slides

### ISSUE THREAD

**Issue by aEyoJeyo** [vassbo/freeshow#186]
I updated to the latest version because of the app freezes when I edit the transition of slides. But when I have the update the transition of the media was off, I think. I was making the text having no transition, but the media went of starting again or pausing when I click to another slide.

I hope you can fix this as soon as possible. I was already using transitions since I have used the app. More power to you. Thanks!

**Comment by vassbo** [comment]
Oh, I see. I'll fix this.
