### ISSUE TITLE
Template Editor: Add Quick Options for Outline

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#189]
Using Linux, v 0.9.1.

Updating a template, attempting to change the border on a textbox, I was puzzled why there was still a white border. Turns out, there's a separate CSS property for `outline`. I can manually adjust the CSS for now, but it would be nice to have quick options above the CSS box for adjusting the outline, similar to how the other properties are edited.

![image](https://github.com/vassbo/freeshow/assets/39384515/acf773a0-7a1b-4a55-bf7d-c3b4bcf5065b)

**Comment by vassbo** [comment]
Thanks. I guess that's just my fault when creating the templates. There is no need to set the outline when you can set the border. I will fix the templates.
