### ISSUE TITLE
Importing ProPresenter 7 (.pro) Files: Occasional Failure

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#195]
ProPresenter import typically works well (not to mention incredibly fast!), but now and then I have a song that won't import. If I am trying to import more than one song at a time, the single "bad" file causes the whole group not to import.

![image](https://github.com/vassbo/freeshow/assets/39384515/b735b186-56a6-4ee1-89bf-800b23a270ee)

Attached is one such song, **Anthem**, which fails to import.
[Anthem.zip](https://github.com/vassbo/freeshow/files/11926784/Anthem.zip)

I don't know what's different about this one as compared to others, but it won't import. I'm also attaching a similarly-configured song, **Behold Him**, that *does* work, for comparison.
[Build My Life.zip](https://github.com/vassbo/freeshow/files/11926789/Build.My.Life.zip)

**Comment by vassbo** [comment]
Thanks, I'll take a look.
