### ISSUE TITLE
Searching for the book of "John" does nothing.

### ISSUE THREAD

**Issue by wallebt** [vassbo/freeshow#199]
When using the scripture tab, I can search every book of the bible with the quick search but when it comes to the book of John, nothing, even if I type it out. If I manually selected from the window, no problem. I just can't quick search it.

I am using NIV XML from beblia.com

Thanks brother!

**Comment by vassbo** [comment]
The issue was that it was finding "1 John", "2 John" and "3 John" as well.
It should work fine in the latest version! :)
