### ISSUE TITLE
FreeShow hangs when saving after importing OpenLP Songs

### ISSUE THREAD

**Issue by dantyndall** [vassbo/freeshow#200]
I'm having an issue where FreeShow will hang when saving after opening OpenLP Songs. I thought this issue might be much more generic, and related to my non-standard configuration of mapping my Windows 10 Documents folder to a Documents folder within my OneDrive... but I don't think that's the case. I have attempted to map the FreeShow save folders to a local folder that sits at the top of the C:\ drive. Once I imported an OpenLP song though, and saved, I got issues. Any idea on what's going wrong, or what data I can provide you to help you further diagnose the issue?

**Comment by dantyndall** [comment]
[OpenLP_Export_Songs.zip](https://github.com/vassbo/freeshow/files/12002848/OpenLP_Export_Songs.zip)

Here are the songs that I was trying to import. II appreciate you looking in to this!

**Comment by vassbo** [comment]
It will probably be a few weeks until the next update, but I should hopefull get it fixed by then.

**Comment by dantyndall** [comment]
I understand--I was hoping to be able to use it for Royal Family Kids Camp in two weeks, but may just have to use OpenLP for one last camp.

This looks like a great program though, and I look forward to seeing other updates in the future! Thank you for all that you are doing!

**Comment by vassbo** [comment]
Thanks! Are you using windows? I might be able to give you an exclusive build, if it's an easy fix.

**Comment by dantyndall** [comment]
Yep, I am using Windows 10 Pro.

**Comment by vassbo** [comment]
Okay, great! I'll try to fix it and send it over when I have time. 😊

**Comment by vassbo** [comment]
I just tried importing the songs you sent over, and it worked just fine for me, even after saving.

Try deleting the programs data in C:\...\AppData\Roaming\freeshow. And try importing the songs without changing the "Shows" folder path.

If it works then I guess the problem might with the OneDrive folder.

**Comment by dantyndall** [comment]
Fascinating. It worked for me. A further update... it looks like I also tried moving the songs out of the OpenLP category, and into a RFKC Songs category. Saving after that seems to be what is causing the hang. I guess I won't do that then! :)

**Comment by dantyndall** [comment]
By the way, after I get into a hanging issue, and force close the app, restarting it just makes it hang again. I have to uninstall it, reboot, and re-install it to get it functional again. Is there an easier way of skipping some of these steps? I tried deleting the freeshow folder in %APPDATA% (based on your suggestion above), and restarting, but still seeing the same issue. Are there any other folders I should try removing, so I don't have to do the reinstall/reboot cycle?

**Comment by vassbo** [comment]
Okay, great! I'll fix it so you can move them to another category, just keep them there for now.

I guess it should work as long as you don't change the category of any imported shows.

Most of the times a restart of the program fixes freezing, but if not try deleting the "shows.json" file in the AppData folder. Then if it doesn't freeze go to settings, choose "Other", then click refresh shows from folder.

**Comment by vassbo** [comment]
Let me know if you still have some issues related to this, I hope it's fixed!
