### ISSUE TITLE
Media will not clear

### ISSUE THREAD

**Issue by wallebt** [vassbo/freeshow#202]
Everytime I click on a new media file, it will not clear unless I close and re-open the software. This makes adding backgrounds a no go at the moment.

I've tired drag and drop, drag and drop into a blank slide, adding a media item to a blank slide. Sometimes it works, most of the time, it does not. 

Am I missing something?

Thanks for all the hard work! :)

**Comment by vassbo** [comment]
I have seen it not clearing on the preview screen. But not in the output.

I recommend setting media as backgrounds with drag and drop, and not the media element.

Do you click on the clear all button when the output window was active?

**Comment by wallebt** [comment]
What do you mean setting media as background? Drag and drop into a slide or as a slide or by selection media inside a slide as an item?

Yes I did click it :)

**Comment by vassbo** [comment]
When you drag a media file from the drawer, or the computer onto a slide it will be added as a background on that slide and all following slides. If you drop in the show, but not on a slide it will create a new slide with a background. I have not had any issues with this myself.

Maybe you can send a video so I can see what is going on, and maybe fix the issue. 😊
