### ISSUE TITLE
USB audio input on Mac not visible

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#205]
Freeshow Version 9.2
Running on MacOS 10.15.7

I have an external audio source (our audio board) coming into the computer via USB.

I have confirmed that the audio input is visible in the computer settings, but the **Audio** tab of the bottom drawer does not list anything.

I can confirm that in other programs, the audio feed is visible and works as expected.

**Comment by vassbo** [comment]
Did you add any folder from the external drive?

**Comment by jdcarls2** [comment]
It's a live audio input, not audio files, does that make a difference?

**Comment by vassbo** [comment]
Oh, have you checked the "Microphones" section in the "Live" drawer tab?

**Comment by jdcarls2** [comment]
Oh, gosh. I didn't even notice that! Well, that's an easy issue to close, then!
🤦‍♂️
