### ISSUE TITLE
Feature Request: Video Feed as Slide Item

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#207]
I would love to add a video feed to a slide in the same way that I add a **media** item.

Before our service starts, we like to have our announcements running in a loop, but with a small thumbnail of the sanctuary camera in the corner.

Right now, there doesn't seem to be a way to do this in Freeshow, unless I have missed something.

**Comment by jdcarls2** [comment]
To be a little more clear: I would like the video feed to be movable, selectable, resizable, etc., not just a background.

**Comment by vassbo** [comment]
Good suggestion! I'll see what I can do.
