### ISSUE TITLE
Bug: Drawer tab gets "stuck" in Mac, Windows

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#209]
Freeshow 0.92 on both Mac and Windows, the drawer tab sometimes seems to get "stuck", and clicking other tabs won't switch. I'll click over to "Timers", for instance, and then cannot click back to "Shows".

The keyboard shortcut still works, but often I will just click repeatedly (2 or 3 times) on the other tab that I want, and it gets unstuck! The problem is, this will frequently register as an additional click on the newly-activated tab, which then minimizes the drawer, so it gets to be a little annoying.

**Comment by vassbo** [comment]
Thanks. I'll fix this.

**Comment by vassbo** [comment]
The tabs did not open because the mouse moved after pressing down, even just one pixel. But I changed it back so it opens even when the mouse moves.
