### ISSUE TITLE
Templates and Slides

### ISSUE THREAD

**Issue by thebiblelover7** [vassbo/freeshow#21]
As of right now, if I understand correctly, Slides have all of their formatting stored in themselves. So far, you *can* apply templates, but that can cause some issues. Also, looking forward, it would be great to have the ability to do **multiple outputs**. Changing the way that templates work would help in that regard (imo).

To summarize, it would be nice for slides to only store the "text, media, etc", but *not* the formatting. Templates would then define *how* the slides look.

**Comment by vassbo** [comment]
Thank you for the suggestions. Multiple outputs is a planned feature.

Also currently the way templates work is that if you apply a template to a show, the show should automatically update with any changes on the template. If you make changes to a single slide the template will no longer be active in the show.
It's nice to not always have a template if you want to create a presentation.

But maybe I will add an option to override the output with a template when I add multiple outputs.
