### ISSUE TITLE
Duplicating and then deleting

### ISSUE THREAD

**Issue by odlg** [vassbo/freeshow#212]
Seeing some non-logic behavior. 
When pressing the Verse 1 or Verse 2 buttons the verses duplicates - is that intended?
When attempting to delete the duplicates, all verses with same text are deleted - is that intended?
See attached screencast.

**Comment by odlg** [comment]
Screencast

**Comment by odlg** [comment]
Screencast:
https://github.com/vassbo/freeshow/assets/2950255/ed695bef-58c9-4696-9f4b-1950768de5d4

**Comment by vassbo** [comment]
Yep. That's intended, because you can then reuse the same e.g. Chorus, and change all of them at the same time. If you don't want that you can just duplicate the group, instead of reusing the same group!
