### ISSUE TITLE
Show Category Customization

### ISSUE THREAD

**Issue by aJaaaang** [vassbo/freeshow#213]
I suggest when adding a new category, you can customize it first rather than renaming it and adding it an icon after adding.

What I mean is when adding a new category, there must be a "just like system" where you can name it first and add an icon. It makes us faster when adding some Show Categories. I know it's not a big problem and important this is, but I am just suggesting. :)

Thanks for your hard work! More power! God bless.

**Comment by vassbo** [comment]
Thanks. I'll see what I can do.

**Comment by vassbo** [comment]
I changed it so it will highlight the name input by default, so you can just type the name directly after creating.
To change the icon you can just click on the actual icon on the left.
