### ISSUE TITLE
Custom Icons

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#215]
I just submitted another issue, and I have a feature request that could address it in a different way. **Custom Icons**.

The icon library pops up when you are setting the icon somewhere, or adding it as a slide item.

![image](https://github.com/vassbo/freeshow/assets/39384515/9da68ef7-3dec-4bda-a6dd-ddfd9725cde7)

What I would love is somewhere to actually _manage_ the icons, like another tab in the drawer. If I could add a custom icon, maybe by pasting the SVG or something? I don't need most of the built-in icons, and also wouldn't mind removing some. But if I could add SVGs of my church logo, or other icons, that would be amazing.

**Comment by vassbo** [comment]
Sounds like a nice feature.

**Comment by DrippingDumpsterJuice** [comment]
maybe an easy way to partially expand its functionality would be to allow any unicode character to be added as an icon?

**Comment by vassbo** [comment]
Maybe, I'll see. 🤔
