### ISSUE TITLE
Ctrl + ? to bring up Shortcuts

### ISSUE THREAD

**Issue by jdcarls2** [vassbo/freeshow#216]
Recently, I accidentally moved an output to my main screen, and couldn't see the button to deactivate it! I knew there was a way to deactivate outputs with a shortcut, but I couldn't see the menu bar to open it, so I was just guessing keyboard shortcuts for a while.

In a lot of apps, <kbd>Ctrl</kbd> + <kbd>?</kbd> brings up the keyboard shortcuts screen. Might be a nice enhancement to include.

**Comment by vassbo** [comment]
I'll see. You can just double click the output window to hide it!

**Comment by jdcarls2** [comment]
Yes, I found that out! The problem was my own doing, really, so it's not a bug or anything.
