### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by ITMan101** [vassbo/freeshow#220]
For youth events, we will often do games that have scoring. This could be within the timers menu.

Feature Request:

- Be able to name the counter (i.e. Blue Team)
- Ability to manually set the current counter value without entering another UI
- Increment and Decrement buttons
- Ability to customize the Increment/Decrement amount without entering another UI
- The value is linked and automatically updated on slides

**Comment by vassbo** [comment]
Hmm... I have thought of doing something like this. I will see how this can be added.

**Comment by vassbo** [comment]
I added a "Variables" tab that can be found in the "Overlays" drawer tab. 🤩
Here you can currently add numbers as you described, and text.
Then just add a "Variable" item to any slide and choose a variable!

I also made it so you can use math expressions to change any number input value, meaning if the "score" is "10". You can type "10+2.5", then the number becomes "12.5"! 😊
