### ISSUE TITLE
Timer sounds

### ISSUE THREAD

**Issue by ITMan101** [vassbo/freeshow#221]
For youth games, it would be cool to be able to set an audio file to play while the timer is counting and a sound for when the timer finishes.

**Comment by vassbo** [comment]
Nice suggestion! You can drag an audio file to the slide that can start at the same time as the slider, but I will probably make it so "Next after media" jumps to the next slide when the timer reaches 0, so you can have another sound on the following slide.

**Comment by vassbo** [comment]
You can now do this in the latest version! 🤩

Here is a visual example of how I would do it:
![image](https://github.com/vassbo/freeshow/assets/17619496/9b9b0c50-b38b-4093-9d7a-28ecb7a9218a)
