### ISSUE TITLE
Adding Current Slide Output as a Connection

### ISSUE THREAD

**Issue by kinghamr** [vassbo/freeshow#223]
Is it possible to add a "CurrentShow" Output to use on Web Browsers in case if there is an outdoor service and don't want to mess with the "StageShow" view but want our audience to use their phones or tablets or devices to see the words or if the projection device dies? There will be a local hotspot provided just in case if this happens.

**Comment by vassbo** [comment]
Could be a nice feature. I'll see what I can do.

**Comment by vassbo** [comment]
Remote output is here! 🤩

It's turned off by default in the "Connection" settings.
You also have to have the output window active for it to work, because it records the output screen and streams to any connected devices!
