### ISSUE TITLE
Multilingual propresenter files imports partially

### ISSUE THREAD

**Issue by odlg** [vassbo/freeshow#224]
Importing a multilingual propresenter files only imports it partially, some slides are missing. Files created like this: https://churchmediadrop.com/multilingual-propresenter/ 
I can send you examples if needed.

**Comment by vassbo** [comment]
Please send over a file that don't work, and I'll check it out.

**Comment by odlg** [comment]
Example 1 - screenshot from propresenter 7.xx and freeshow 0.9.3
<img width="1218" alt="Screenshot 2023-07-21 at 07 48 07" src="https://github.com/vassbo/freeshow/assets/2950255/70905e5c-58af-4a05-a5b4-3b4ae7e5e90c">
![Screenshot from 2023-07-30 13-28-28](https://github.com/vassbo/freeshow/assets/2950255/6c2c44eb-a481-47cb-8245-6b88a53a7158)

[example1.zip](https://github.com/vassbo/freeshow/files/12209062/example1.zip)

**Comment by odlg** [comment]
Another example with screenshots:
<img width="1138" alt="Screenshot 2023-07-21 at 07 46 57" src="https://github.com/vassbo/freeshow/assets/2950255/11312c14-eaa1-4cd1-859e-d2e1dcb05935">
![Screenshot from 2023-07-30 13-28-13](https://github.com/vassbo/freeshow/assets/2950255/1bd00026-a878-4af7-a402-c36f4a408973)

[example2.zip](https://github.com/vassbo/freeshow/files/12209075/example2.zip)

Some slides are missing and some encoding issues.

**Comment by odlg** [comment]
Stage view puts both texts upon each other when using multilingual like this.
Editing the slides and making multiple changes in both texts and then undoing does not revert correctly.

**Comment by vassbo** [comment]
The stage is only an issue in the preview, but it is fixed for the next version.
Undoing might not always work as expected currently, but should be generally fine.

I also have fixed æøå not being formatted correctly for the next version.
In my testing all the slides imported correctly, you just needed to change layout on the Cornerstone song, from "New Arrangement" to "form"!

**Comment by vassbo** [comment]
Your issues should be fixed in the latest version! 😊

**Comment by odlg** [comment]
Thanks a lot - looks good. 
It would be good to be able to select just one of the texts for stage. Is there a way to switch which text is first for all slides in a show?

**Comment by vassbo** [comment]
In the "Edit" page, you can go to "Items" on the right side and arrange the items in the order you want them to show up.
I'll probably add an option to to that!
