### ISSUE TITLE
Support HTML item

### ISSUE THREAD

**Issue by filiphanes** [vassbo/freeshow#231]
Hi, I would like to show custom HTML page in slide defined by URL (http(s):// or file://).

**Comment by vassbo** [comment]
Great idea!

**Comment by filiphanes** [comment]
great, that was fast, thanks
going to test ti

**Comment by filiphanes** [comment]
is it working for you?
I am not able to set URL, it forgets it whenever I click away

**Comment by vassbo** [comment]
It works fine for me, at least in a normal show. I'll investigate a bit.

**Comment by vassbo** [comment]
I might have figured it out. Will update tomorrow.
Also I found out that the program was freezing sometimes when the URL was invalid.

**Comment by vassbo** [comment]
Please test it again in the latest version! 😊

**Comment by filiphanes** [comment]
thanks, sometimes it works, sometimes not

**Comment by vassbo** [comment]
Okay, are you doing anything different the times it doesn't work?
