### ISSUE TITLE
VideoPsalm import error

### ISSUE THREAD

**Issue by MrDogeBro** [vassbo/freeshow#235]
## Issue
When importing songbooks from VideoPsalm in v0.9.5, there is a pair of brackets (`[]`) being added at the end of every line. However, importing the same file in v0.9.4 yields the correct result with no brackets at the end. I know its probably a simple fix but I wanted to let you know. I may look into it and see if I can fix it when I get a chance if you haven't already. Screenshots are posted below of the output.

### v0.9.5
![Screenshot 2023-08-17 at 16 58 57](https://github.com/vassbo/freeshow/assets/35872177/4ce04aa3-a22a-4f13-9b22-4df3f0df2e95)

### v0.9.4
![Screenshot 2023-08-17 at 16 59 03](https://github.com/vassbo/freeshow/assets/35872177/081fd067-6282-4bbf-a243-623f3d6475b3)

## Side Note
Side note, but I just wanted to say that I just recently started playing around with this software and its amazing. Really excited to see where it can go. But I also wanted you to know that so far, v0.9.5 is running better than v0.9.4 was for me so good job on that. Thanks.

**Comment by vassbo** [comment]
Awesome! Thank you. I'll release a version with a fix later today! 😊
