### ISSUE TITLE
Multi Bible Projection 

### ISSUE THREAD

**Issue by IsaiahGraham** [vassbo/freeshow#236]
Sorry if this is not the right spot to put feature requests.

Our congregation is mixed English and French speakers. If would be nice if you be able to duel project multiple scripture versions at the same time.

Being able to show English and French at the time would be amazing! 

Thanks for making such a great presentation software.

**Comment by vassbo** [comment]
Thank you! 😊
You can do that, see this: https://freeshow.app/docs/scripture#create-a-collection

![image](https://github.com/vassbo/freeshow/assets/17619496/717c0307-eeac-41ef-be16-0d1a399848a9)

Please ask if you are stuck and need help!

**Comment by noah-sheldon** [comment]
Thanks @vassbo 

What about multilingual lyrics for songs?

**Comment by vassbo** [comment]
@noah-sheldon https://github.com/ChurchApps/FreeShow/issues/793#issuecomment-2326123583
