### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by JayDaq** [vassbo/freeshow#24]
I want to say first, thank you so much for making this software as an alternative to other presentation software like ProPresenter which we can't afford but you are giving this for free.  I hope this will be a successful app and you yourself too.  Godbless to you

anyways I will list the bug that I experienced :
* copy and paste or the CTRL + C or V doesn't work (I don't know if you added this though so it might not be a bug)
* duplicate button is always unavailable or greyed out.
* Deleting using the delete key doesn't work in editing slides.
* sometimes the software is unresponsive as I press things it won't do anything but I can move it through the screens.
* I can't present if I put the app in fullscreen but if not in fullscreen I can present.

hope this helps you.

**Comment by vassbo** [comment]
Thank you. The first three are not fully implemented yet. I will try to add them and fix the last two bugs in the next few updates.

A question, what did you press/do when the program got unresponsive?

**Comment by JayDaq** [comment]
> Thank you. The first three are not fully implemented yet. I will try to add them and fix the last two bugs in the next few updates.
> 
> A question, what did you press/do when the program got unresponsive?

Just editing slides and navigating and all the sudden when I press some buttons it doesn't respond and when I press the exit button it just lights up and won't exit

it might be just my computer idk.

**Comment by vassbo** [comment]
Okay, I'll do some tests. It's probably not your computer.

**Comment by JayDaq** [comment]
I think I got it, so when I edit the slides through the edit section and when you make changes and then ctrl + z until you go back to the show section where everything is gone and that is where it becomes unresponsive

I did it 5 times and 3/5 it does that.

**Comment by vassbo** [comment]
Okay, thanks. The issue is redoing.
