### ISSUE TITLE
Imorting text/songs with åäö

### ISSUE THREAD

**Issue by S1Zr** [vassbo/freeshow#240]
Importing songs with åäö both from text files an from pro-presenter files gives texts with åäö replased with other characters.

Fixing this would be great!

I can provide with files that gives the problems.

**Comment by vassbo** [comment]
Please send some files with these characters, and I'll be able to fix it.

**Comment by S1Zr** [comment]
> Please send some files with these characters, and I'll be able to fix it.

[ProPresenterExport.zip](https://github.com/vassbo/freeshow/files/12447804/ProPresenterExport.zip)
[Så stor är vår Gud.txt](https://github.com/vassbo/freeshow/files/12447811/Sa.stor.ar.var.Gud.txt)

Files attachted.
