### ISSUE TITLE
Independent Notes for Slides

### ISSUE THREAD

**Issue by kinghamr** [vassbo/freeshow#241]
Is there a way for notes to be for each slide in the show music file instead of being for the whole entire slide show set?

**Comment by vassbo** [comment]
Could you explain further? You can add independent chords to slides.

**Comment by kinghamr** [comment]
In the previous versions, I could set different notes for every slide, but
in this recent version, it won't let me create notes for some reason.

**Comment by vassbo** [comment]
You have to first enable "Chords" mode in the bottom of the "Edit" page. then just click any letter in a verse to create a chord.
