### ISSUE TITLE
Feature Request: OnSong Imports

### ISSUE THREAD

**Issue by MrDogeBro** [vassbo/freeshow#245]
It would be nice to be able to import [OnSong](https://onsongapp.com/) files that have the extension `.onsong` into FreeShow. I know that the OnSong files are similar to ChordPro files, so I was able to make a quick Python script in order to roughly convert them to a rough ChordPro file, which is not perfect but it works good enough for now. However, it would be amazing if FreeShow could natively import the OnSong files, like it can with many other formats and software specific file formats already.

Let me know if you have any questions, but I think it would not be too difficult to implement, but would allow for greater compatibility. Thanks.

**Comment by vassbo** [comment]
This should be fine. Are you able to send over a couple of example files I can use?

**Comment by vassbo** [comment]
I added .onsong files to the ChordPro import.

**Comment by MrDogeBro** [comment]
Thank you! Sorry I didn't get back to you sooner.
