### ISSUE TITLE
Lyrics View editor

### ISSUE THREAD

**Issue by ejbramos** [vassbo/freeshow#247]
I am not pretty sure if it is a bug or a suggestion or there is a limition regarding the software

There are some parts of the song that I want to edit especially with its format but whenever I try editing using the Lyrics view, it reformats or reverts as the song initially formatted. Please refer to the video that is attached below. 

PS. Disregard my voice but refer to the video of what am I illustrating 

Link of the Video: https://drive.google.com/file/d/1YWcT8ivnr0DwjxQAckIFHrTAZgfjlaRx/view?usp=sharing

Software Details:
Freeshow v0.9.6

**Comment by vassbo** [comment]
Okay, thanks. I'll see if this can be fixed.
