### ISSUE TITLE
Showing Powerpoint, Google slides, Canva presentations, etc using Embedded link

### ISSUE THREAD

**Issue by sbridgett** [vassbo/freeshow#251]
Thank you for developing FreeShow, which is good. I downloaded it today and was testing it.

I know that FreeShow can import the text from PowerPoint files, and can import via a PDF export from Powerpoint.

However, as FreeShow uses Electron (so uses HTML, JS, CSS), and FreeShow can already show online media (Youtube, Vimeo, etc), I wondered if you had considered showing Embedded iframe codes from Microsoft 365 (ie. online powerpoint file, then selected File -> Share -> Embed), and similarly for Google Slides embed codes, and Canva embed codes, etc.

The embed codes are used for embedding the show in a webpage, but I think would also work inside Electron, if the iframe height and width are set to match the screen size?

The animations within the powerpoint would work in the embedded show (whereas animations don't work with images).

The speaker who prepared the powerpoint could share the powerpoint via the Embed weblink (rather than needing to email the full powerpoint file or use a USB memory stick).

I think Microsoft 365 has a reduced fee for non-profits such as churches, and Google Slides is free to use. 

I've used the Microsoft 365 embed code in a webpage and it works okay.  I can look into how the embed codes can be used in electron if that is of help?

**Comment by vassbo** [comment]
Thank you! Good idea.
I realised that you are actually able to do this with the **Website** item. Just make sure to only paste the URL inside the `src=""`, and not the entire iframe. 😊

**Comment by sbridgett** [comment]
Thank you for replying so quickly. That is a good idea to put the embed url src="" part into a Website item. 

However when I use that https://..... link directly in the Website URL, FreeShow shows the Microsoft online login page. (Whereas when I enter, eg: https://google.com in the Website URL it displays okay.

When I then enter that https:// link directly in my web-browser url bar, it opens the powerpoint in edit mode. 

I think that Microsoft must detect if the link is coming from within an <iframe src="....."> and then it is displayed the powerpoint as the embedded view, whereas if not inside an iframe then it displays the powerpoint in the full edit mode, which requires logging in.

I had set the online powerpoint file to be "anyone with the link can view", but even when I set it to "anyone with the link can Edit", it still shows microsoft onedrive log-in within the FreeShow preview.

**Comment by vassbo** [comment]
It is iframe. But you have to get the url from inside the iframe. Not the link to the PowerPoint, but to the embed src, just remove the iframe part after copying. I tested it, and it worked.

**Comment by sbridgett** [comment]
I think I discovered the reason. There are two possible embed url links on Microsoft sharepoint:

(1) Using 'https://...............&amp;action=embedview&amp;wdAr=.....'
as below (I've changed part to just ........):
```
<iframe src="https://........sharepoint.com/............./Doc.aspx?sourcedoc={abc12345-..................7890}&amp;action=embedview&amp;wdAr=1.7...." width="1000px"
height="500px" frameborder="0"></iframe>
```

when entering the above in the FreeShow Website URL, need to replace:  `&amp;` with: `&`
and (optionally) replace:
`{` with: `%7B`
`}` with: `&7D`


and 
(2) Using "https://.......?UniqueId=..."

`<iframe src="https://........sharepoint.com/............./embed.aspx?UniqueId=abc12345-..................7890" width="1000" height="500" frameborder="0" scrolling="no" allowfullscreen title="Title"></iframe>`

and that https url can be entered into the FreeShow URL without any changes as doesn't contain any `&amp;` symbols.


I think the `&amp;` can be used within an `iframe src`, but not in webbrowser url, so need changed to `&` first, as otherwise the webserver think the `amp;`  after the `&` is the parameter name, so ignores the `action=embedview`

**Comment by vassbo** [comment]
Okay, great! I'll see if I can auto convert the url.
