### ISSUE TITLE
Holy bible in Portuguese version

### ISSUE THREAD

**Issue by dennis-rocha** [vassbo/freeshow#255]
Hi,

I’m need use the Bible in Portuguese (pt-br) version, but on app the Bible version “translation for translators in Brazilian Portuguese” have New Testament. No have Old Testament in that version.

Can you help me?

Kings regards,
Dennis Rocha.

**Comment by vassbo** [comment]
All the bibles included are provided by Bible.API, I can't change them.
So you need to import your own in .xml format. You can search the web so find some.
