### ISSUE TITLE
New show window closes when drag selecting text outside of box

### ISSUE THREAD

**Issue by BJohnBraddock** [vassbo/freeshow#26]
See title and video. 

Use case: Dragging to select a portion of lyrics to remove, dragged a little too far outside of the box and released and window closes. (I assume clicking outside of the box is a way to close it.) Results in lost progress making minor edits to the pasted lyrics. 

Thanks for all your work in this! Look forward to its success.

https://user-images.githubusercontent.com/69231844/170851872-81f7783c-eea8-4ad6-9fe4-8e80481264b1.mp4

**Comment by vassbo** [comment]
Thank you. I will fix this issue in the next update. 😄
