### ISSUE TITLE
unresponsive when loading an existing Show

### ISSUE THREAD

**Issue by JayDaq** [vassbo/freeshow#30]
Hi, it's me again. Thank you so much for the latest update. You did so well. God bless you for doing this.

There is another bug that is unresponsive when opening an existing show and the show contains a full lyric. Here's a video of it. It also exist in 0.3.4. Hope it help

https://user-images.githubusercontent.com/105600773/174446759-8c566147-12ac-4d20-baf2-54593fab452e.mp4

s

**Comment by vassbo** [comment]
Thank you. I think it might be because the show has an old configuration. Could you send over the .show file, located in your Documents/Shows folder? And I'll look into it. 😄

**Comment by JayDaq** [comment]
> Thank you. I think it might be because the show has an old configuration. Could you send over the .show file, located in your Documents/Shows folder? And I'll look into it. 😄

Oh no, I deleted it after recording. I'm very sorry

**Comment by vassbo** [comment]
Oh, no problem. I think the freezing was only for old shows, meaning this is not an issue anymore for newly created shows. If you create the same song again, save it and open the app it should work. Am I correct?

**Comment by JayDaq** [comment]
> 

yeah, I did try to make a new show and it didn't freeze. Thank you
