### ISSUE TITLE
All dates in the calendar tab are not correct

### ISSUE THREAD

**Issue by nerd0ne** [vassbo/freeshow#32]
When clicking on a date, the sidebar shows the wrong date.

![image](https://user-images.githubusercontent.com/103904665/176789248-cf4ae526-a8c7-411f-a43b-5cccf97efcf0.png)

**Comment by vassbo** [comment]
Thanks, will look into it. 😊

**Comment by vassbo** [comment]
Hey, can you check that this is fixed in the latest version. I can't check because I am not in your timezone. :)

**Comment by nerd0ne** [comment]
Will do.

**Comment by nerd0ne** [comment]
Dates are fixed.
