### ISSUE TITLE
When clicking the present button, it shows an error.

### ISSUE THREAD

**Issue by nerd0ne** [vassbo/freeshow#34]
When clicking the present button, it shows this error, I do not have a second monitor plugged in or a projector, so this could be the reason for this error.

**Comment by nerd0ne** [comment]
![image](https://user-images.githubusercontent.com/103904665/176888828-8a520c16-0efe-42c4-8e77-8deb6ad82541.png)

**Comment by vassbo** [comment]
This should be fixed but let me know if the error still occurs.

**Comment by nerd0ne** [comment]
New error:

![image](https://user-images.githubusercontent.com/103904665/177012330-7457afcb-cc0d-43df-ac69-16a586a91425.png)

**Comment by vassbo** [comment]
Thanks will look into it. 😃

**Comment by vassbo** [comment]
Can you check if this error still occurs?
