### ISSUE TITLE
When selecting multiple dates, an event should say the date beside it.

### ISSUE THREAD

**Issue by nerd0ne** [vassbo/freeshow#36]
When selecting multiple dates, an event should say the date beside it, Like "• e - Jan. 13"

![image](https://user-images.githubusercontent.com/103904665/177012442-9fc13b34-f278-4d99-870d-eda0834b0eb3.png)

**Comment by vassbo** [comment]
I think it does if you select more than one event. 🤔

**Comment by nerd0ne** [comment]
It does.
