### ISSUE TITLE
On remoteshow, clicking on a presentation will make everything in every tab disappear in remoteshow.

### ISSUE THREAD

**Issue by nerd0ne** [vassbo/freeshow#37]
On remoteshow, clicking on a presentation will make everything in every tab disappear in remoteshow:

![image](https://user-images.githubusercontent.com/103904665/177014513-46b19915-2112-4cfa-a4e9-a84e50ad2e68.png)

**Comment by vassbo** [comment]
Hmm, I can't recreate this bug. Can you right click and press "Inspect", then go to "Console", and send a screenshot of any error in the dev tools.

**Comment by nerd0ne** [comment]
![image](https://user-images.githubusercontent.com/103904665/177016260-5443c4bd-550d-4c23-8153-18aa6c28cfca.png)

**Comment by nerd0ne** [comment]
![image](https://user-images.githubusercontent.com/103904665/177016287-80851e10-fc04-4a14-8543-065f7ad7f3ea.png)

**Comment by nerd0ne** [comment]
![image](https://user-images.githubusercontent.com/103904665/177016339-a1f1244b-5807-4e2f-b087-d9a7be041e22.png)

**Comment by vassbo** [comment]
Thank you. 😁 I will see what I can do about it.
