### ISSUE TITLE
All cameras show the same output in menu.

### ISSUE THREAD

**Issue by nerd0ne** [vassbo/freeshow#39]
![image](https://user-images.githubusercontent.com/103904665/177016716-344123ea-bf2e-4966-bed1-60e744ae0a48.png)

**Comment by nerd0ne** [comment]
When clicking the cams. it shows the right output in the show view, but not in the menu.

**Comment by vassbo** [comment]
I have noticed this, but struggled to find a solution. But I will continue trying.
