### ISSUE TITLE
Clicking on this tab will soft lock the program.

### ISSUE THREAD

**Issue by nerd0ne** [vassbo/freeshow#41]
Click on the tab, (tab shown below), will soft lock freeshow.
![image](https://user-images.githubusercontent.com/103904665/180860331-998065aa-ef71-4d22-aab6-8071ee907d40.png)

**Comment by vassbo** [comment]
Hmm. That's the draw tab. It works fine on my computer. I'll do some tests sometime. Thank you. 😊

**Comment by vassbo** [comment]
If you still get this error, try deleting the settings file in AppData/Roaming/freeshow/settings.json. And check if it works.
