### ISSUE TITLE
System Wide Slide Resolution

### ISSUE THREAD

**Issue by Bagel94** [vassbo/freeshow#423]
Hello,

At some point, would it be possible to add a system wide setting that sets the resolution of the Shows? I know in the settings for each show you can set this, but it would be nice to have it in the general settings. So, that when you create new shows, the slide is the proper size and text does not overhang. (See image)

Just want to clarify, that I am not asking about output settings, and I know styles can fix the output size changes, but more on how slides appear within the program when selecting and editing. Because it seems like the default slide size is set to 1920x1080. I also know that templates can rectify this as well but would still be nice to have it from the start. 

Only asking because our church has different screen sizes then those at our homes, and then requires us to reformat items to be displayed properly at the church.

![image](https://github.com/ChurchApps/FreeShow/assets/73187905/f9604f84-4b86-4cdd-b9df-92bc11f114a2)

**Comment by vassbo** [comment]
If the slides have been changed inividually to a custom resolution (e.g. using a template) you will have to reset them using the "Reset" in the "Slide" tools, before it will update according to the resolution in the styles settings.
