### ISSUE TITLE
Freeshow 0.5.0 Program does not exit or quit on Mac OS Big Sur 11.6.8

### ISSUE THREAD

**Issue by jollygudfellow** [vassbo/freeshow#43]
at times, the program does not respond and clicking on multiple objects in the window does not give any preview or output on second screen.
Therefore, when I try to quit the program to start again, it does not respond and stays on the screen and keeps running. 
 "force quit" is the only way to quit the program every time when I start Freeshow. Thats not a great experience!

**Comment by vassbo** [comment]
Thanks. 😊 Does the program quit properly when it's not freezed?

When it freezes there is no other option than to force quit. I will try to fix more of the freezing issues. I have already fixed a few. One thing that causes freezing now is undo/redo, because I haven't implemented it properly yet.

**Comment by jollygudfellow** [comment]
No. Even when the program is not frozen, it does not quit and it runs in the background. So I when I exit and it does not exit, I cannot open the program again!
So I have to force quit from the Apple menu dropdowm. After that when I open the program, it works fine. All these are not related to program freeze issues. These are general issues.

Now coming to the freeze issues:
1. Sometimes when I try selecting a video as background for a scripture, it freezes.
2. Sometimes when I switch the video background when the output window is active, the entire program freezes. So these days I just decide and keep a single image/video as background for song or scripture.
3. After giving 2 lines or 3 lines for song import, I went and edited the lines in the slide and made it 4 lines in 1 slide. After that the "show" never worked. So I had to delete the show and create a new one and copied the song. 
It works the other way round. i.e. if we give song import in each slide as 3 lines, and if we go and edit and make it 2 lines per slide later in "edit", there is no problem at all. (Problem is only visible when we edit and make it more than what we give in default import settings)

**Comment by vassbo** [comment]
Okay, thanks. 😃 I'll see what I can do about the closing, and all the freezing issues.

**Comment by jollygudfellow** [comment]
Thats not a problem. Eagerly waiting. 
Considering the development has been so fast and that the 1st release was only in Feb 2022, it's been an amazing work. Hope very soon Freeshow will be adopted by many groups and churches. The quality is commendable.

**Comment by vassbo** [comment]
Thanks a lot! 😊

**Comment by jollygudfellow** [comment]
I am now using updated 0.5.2 version and its fixed. Thank you.
