### ISSUE TITLE
Font style

### ISSUE THREAD

**Issue by Mike-Christ** [vassbo/freeshow#44]
Hello
My name is Mike and I compliment you for all the work that has been done.
I tested your worship presentation software, that is FreeShow, and I find it really interesting.
I tested that in a Windows computer. But I was able to verify while using the impossibility to use other font styles than those of your softwrare. And I work with several font styles, and Bebas Neue font style primarily.

In a new version of your software, should it be possible to use font styles installed in the computer or should it be possible to install the Bebas Neue font style. Please find attached the Bebas Neue font style to this message.

[bebas_neue.zip](https://github.com/vassbo/freeshow/files/9291422/bebas_neue.zip)

Best regards, Mike.

**Comment by vassbo** [comment]
Hi, thank you. 😊 Using fonts from the computer is on the todo-list and should be added in one of the next versions.
