### ISSUE TITLE
SALIDA SIN AUDIO

### ISSUE THREAD

**Issue by playmepe** [vassbo/freeshow#46]
La version 0.5.1 sin audio en la salida tanto en windows como linux, como se configura el audio?, tampoco se puede visualizar el contenido de las carpetas de medios. 
![image](https://user-images.githubusercontent.com/13964250/184563246-54c77652-10a4-43e2-a092-0bc17d1b073c.png)

**Comment by vassbo** [comment]
Thanks, I will fix this!
