### ISSUE TITLE
automatic date overlay

### ISSUE THREAD

**Issue by stodd10478** [vassbo/freeshow#465]
I love how the application is evolving, the team is doing great!!
I have a feature request.

Would love to see a date overlay like the time overlay; but make both of them user-customizable with shell script

similar to : NOW="$(date +"%m-%d-%Y")"

Keep up the great work!

**Comment by vassbo** [comment]
Thanks. 😊👍

**Comment by vassbo** [comment]
Can be added in the next update using "Dynamic values" (right click textbox when editing).
E.g: {time_date}.{time_month}.{time_year} - {time_hours}:{time_minutes}:{time_seconds}
