### ISSUE TITLE
problemas en la version 0.5.2

### ISSUE THREAD

**Issue by playmepe** [vassbo/freeshow#48]
Hola, te doy alcance de problemas en la version 0.5.2:
- hay problema con algunos videos; en vista previa si se reproducen pero no se reproducen en la salida. 
- Al cambiar de un video a otra, el nuevo video no inicia desde el inicio, sino desde el tiempo en que estaba el primer video.
- El problema mayor es cuando una carpeta tiene mayor cantidad de archivos de video, el consumo de cpu se incrementa demaciado hasta llegar a bloquear todo, la única forma es apagar bruscamente el cpu y volver a iniciar. con carpetas con pocos (entre 5 a 10) archivos funciona bién.
- mi laptop es Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz, Ram 8GB con windows y linux manjaro

**Comment by vassbo** [comment]
Thanks. I will try to fix these issues. I have noticed the last issue, and have tried a few things to make it better, but will continue trying to find a solution.
