### ISSUE TITLE
Issue with setting up codebase

### ISSUE THREAD

**Issue by dev-olly** [vassbo/freeshow#50]
Hi Vassbo, I recently discovered some bugs and would love to fix them, but i am having issues setting up the app, first issue was with the `build:electron:dev` command, 

```
error TS7016: Could not find a declaration file for module 'builder-util-runtime'. '//Projects/OS/freeshow/node_modules/builder-util-runtime/out/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/builder-util-runtime` if it exists or add a new declaration (.d.ts) file containing `declare module 'builder-util-runtime';`
```

had to disable the `noImplicitAny` for now, but even after that, when i run `start:electron`, i get a whole new set of error

```
App threw an error during load
Error: Cannot find module 'OS/freeshow/node_modules/sqlite3/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node'
```

I suspect it's because of i am on an M1 machine. Do you have any workaround or docs you could share. Thanks

**Comment by vassbo** [comment]
Awesome! I'm happy for any help.

The run command should be just "npm start", try that.

But it might not work because of the M1 processor, I have only tested the codebase on windows. Here is a related issue that might help: https://github.com/TryGhost/node-sqlite3/issues/906

**Comment by dev-olly** [comment]
Yeah, i ran the `start` command first, i'll set it up on my windows machine tomorrow and get back to you. Thanks

**Comment by vassbo** [comment]
Did you get it working? I have to apologize for the messy code, I know it's hard to read right now. 🤪 I do want to clean it up at some point.

**Comment by dev-olly** [comment]
Ah, sorry I haven't gotten back to you yet, currently ill, I'll get back to you as soon as i set it up and no worries about the codes😅
