### ISSUE TITLE
No option to switch from 24 hour time to 12 hour time

### ISSUE THREAD

**Issue by catsdgs** [vassbo/freeshow#52]
This is the best piece of software that I have found in a while! I am helping plant a church and this has saved us! I don't think we will need ProPresenter! There are a few bugs that I have noticed (I might make more issues), but the main thing that has bothered me is that I can't change the clock on the main interface or the stage display to be a 12-hour clock.

**Comment by vassbo** [comment]
Awesome! Thank you. I will definetly add an option to change the time format.
