### ISSUE TITLE
Videos not looping when added to first slide in the show

### ISSUE THREAD

**Issue by catsdgs** [vassbo/freeshow#53]
![image](https://user-images.githubusercontent.com/29613547/185810826-34970315-1557-498f-b1aa-c6561ba80240.png)
The loop button on the media doesn't toggle the loop, so the video stays still after it has ended. I have dragged and dropped the video onto the first slide in the show.

**Comment by catsdgs** [comment]
It worked after restarting. An indicator that it is in loop mode would be nice

**Comment by vassbo** [comment]
That button is actually to set if the video should loop when played. There is another button in the media tab right under the "Clear all" button where you can loop and interact with the current playing video.

**Comment by vassbo** [comment]
Oh, the button should have changed color, and there is a message when you hover over it. But maybe it's broken. I'll check it out.
