### ISSUE TITLE
Cannot copy-paste lyrics when creating a new show in v0.5.3

### ISSUE THREAD

**Issue by jollygudfellow** [vassbo/freeshow#57]
Tried copy-pasting lyrics from the web browser to Freeshow while creating new show and the lyrics cannot be pasted inside the text box where I used to create songs before. Only seen in this version 0.5.3

- I tried pasting it other places. Paste from clipboard works on other apps on the Macbook pro. So Freeshow is unable to paste from clipboard. 
- I have to manually type the lyrics line-by-line to create a show.
- This is also seen when you edit the song later. I cannot copy and paste or cut and paste from one slide to another slide. I have to manually type in one slide to add words or edit them. Also, I have to delete them rather cut them.

**Comment by vassbo** [comment]
Thanks. Seems to be an issue on Mac. I'll look into it.

**Comment by vassbo** [comment]
Is this issue fixed in the latest version?

**Comment by jollygudfellow** [comment]
This issue is fixed with the latest 0.5.4 version. Thank you very much!
