### ISSUE TITLE
Option to present images and lyrics direct from web

### ISSUE THREAD

**Issue by claudemircasa** [vassbo/freeshow#58]
Freeshow is amazing software, it has a lot of potential, but I miss an option to fetch images and lyrics directly from the web. In the "media" tab, there could be a "web" category to search for images from a site with an API free of charge like Pexels. You could save them locally or just use them temporarily. Lyrics could follow the same logic.

**Comment by vassbo** [comment]
Good ideas! I'll see what I can do. 😊

**Comment by jollygudfellow** [comment]
I was selecting the verse colour in version 0.5.4 after selecting the bottom-right template. It does not change anything after I double-click the verse to see in Live view. (Though it shows in the bottom right panel that the colour is updated in the rectangle after selecting from the panel from the dropper tool.)

**Comment by jollygudfellow** [comment]
Or is there a specific way how I should do it?
