### ISSUE TITLE
PDF pages not properly displayed

### ISSUE THREAD

**Issue by soph-os** [vassbo/freeshow#63]
When importing a PDF file with more than 10 pages, the pages 1-9 appear only as black slide without content. Page 10 and all following are as expected.

Platform: Win11 Home - 10.0.22621 Build 22621

**Comment by vassbo** [comment]
Thanks, I'll look into this.

**Comment by soph-os** [comment]
Seems also be a problem in 0.6.0. But fix is easy:
- temporary image export is done with "img-**0**1.png" (By having a PDF with 100+ pages same occurs with "img-001.png")
- Freeshow looks for "img-1.png"

Changing the filenames in Explorer shows directly the files in Freeshow.

**Comment by vassbo** [comment]
Oh, makes sense. Thanks. I think I thought the issue was export first.
