### ISSUE TITLE
Unexpected behavior while editing timer on slide

### ISSUE THREAD

**Issue by soph-os** [vassbo/freeshow#66]
Following steps lead to an unresponsive app with no way to close the timer dialog (and not using the app anymore):

- Add a new timer on a blank slide
- Rightclick on timer => Edit
- Type a new timer name
- Confirm with "edit" => not able to close timer dialog window

**Comment by vassbo** [comment]
Thanks, I'll fix this!

**Comment by vassbo** [comment]
Hi, do you still have this issue in the latest version?

**Comment by soph-os** [comment]
It seems to work now. I think one issue was in my project settings. With a clean show it works now while in one of my old ones the issue still persist.
