### ISSUE TITLE
Unexpected behavior in stage view

### ISSUE THREAD

**Issue by soph-os** [vassbo/freeshow#67]
During checking out the stage view, I encountered following issues (if it is currently WIP then just keep it as a reminder :) :
**Styling:**
- Changing font size or alignment has no (immediate) effect (not sure whether it changes at all, sometimes it does...)
- Font size of slides with multiple text boxes has only effect on first (e.g. scripture text: text is small, but scripture (book, chapter) with bigger font size)
- Stage view output has fixed resolution. Responsive design would be nice.

**Current/Next Slide box:**
 - Inserting fields just display the text, but no graphics/video/images/overlays are shown
 - Scaling the bounding box just crops the content but not scaling it. (Multiview not possible)
 
**General:**
- Timers for video displaying only text "time#video_countdown" but no actual values
- Renaming of stage views: no response/dialog

- Feature: output destination for stage view on different local graphic output to feed the stage monitor from presenting computer

- General: displays with different DPI. Output doesn't care for effective resolution. E.g. 1080p display with 150% DPI scaling results in limited used output size in web browser. Expected behavior: 1080p output is properly scaled to fit even with higher DPI.

**Comment by vassbo** [comment]
Thank you. Stage is one of the main things I havent worked on a lot. I will keep this here until it's done.
