### ISSUE TITLE
Video Sound Only Plays From Right Speaker

### ISSUE THREAD

**Issue by catsdgs** [vassbo/freeshow#68]
All videos that I add to my project will show the sound on the visualizer as if it is coming from the right and left channels, but in reality it is only coming from the right speaker. I have only tested this on Windows.

**Comment by vassbo** [comment]
Oh, thanks. I think the issue appeared when I added the left/right visualizers. I will look into it. 😊

**Comment by Mr-Hayden** [comment]
I'm also having this issue
