### ISSUE TITLE
Past new song - not obeying verses

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#69]
Hi,

I copied a song from google doc and freeshow did not obey the verses defined. I then tried to first paste the song into notepad, copy and then paste into freeshow and I got the same result. Every slide contains no more than two lines.
![image](https://user-images.githubusercontent.com/98491691/195156972-423bde31-8cb1-4906-b5c2-3190765611c6.png)
![image](https://user-images.githubusercontent.com/98491691/195157545-566cd290-b86a-47a3-a06e-e4a93bdab688.png)

I corrected the text size using the template, but still there are just two lines in each slide.
I went into the second slide, copied the text and pasted it into the first slide. It did not accept this action. I had to manually type in the text I wanted.

**Comment by vassbo** [comment]
In settings, under general, there is a setting to increase the amount of imported lines. It's 2 by default. Hope this helps. 😊

**Comment by dajomu1** [comment]
It helps a bit, but I think the feature is not good. It makes more sense to me that the number of lines in each verse pasted is obeyed and if the user wants to split the verse then ok, he can do that. I increased the lines in setting, but it did not change the songs already created, which is fine I believe. But the editor for repairing the song is cumbersome. The song can be deleted and created again, but I think it would be much more user friendly if I could open the song in a view similar to the song creation (see image) and split verses there. This gives an easy access to all verses.
![image](https://user-images.githubusercontent.com/98491691/195316181-82a3540c-f40d-4d6d-919b-9ae82f575e09.png)

**Comment by vassbo** [comment]
Yes, this is actually on the todo-list.
