### ISSUE TITLE
Feature request - Google calendar

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#70]
I wonder if it is possible or if it can be implemented to access a shared google calendar and show the content in the freeshow calendar? I like the monthly view already present, and if it can be filled with content like in google calender (see image) that would be great.
![image](https://user-images.githubusercontent.com/98491691/195159641-7b6dd945-adc0-4412-a96d-fcfff253ddd6.png)

**Comment by vassbo** [comment]
I will se what I can do.

**Comment by vassbo** [comment]
Not quite shared access, but you can download the calendar .ics file and import. (It can also update the events when imported again)
