### ISSUE TITLE
Background is shown on every slide

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#71]
I added a couple of backgrounds to a song. If I click on bullet No.1 the verse is shown with a background as it should. If I click on bullet No. 2, the same background image is shown on live. If I choose a new song bullet 3 and 4 the projection will show the last image clicked on e.g. bullet no. 1.
![image](https://user-images.githubusercontent.com/98491691/195163167-4e188d50-217f-459f-9541-09b918811156.png)

**Comment by dajomu1** [comment]
Forgot to write that I am not testing this using a projector. I am using win10 and single screen.
how do I remove or hide this? 
![image](https://user-images.githubusercontent.com/98491691/195163620-d391288d-4ba6-49dc-bd50-d68beae79805.png)

**Comment by vassbo** [comment]
The way the output works is with layers. There are four main layers, backgrounds, slides (text), overlays and audio. In the right section you can clear all, or if you click two times on the buttons right under the "Clear all" button, you will clear just the one layer. This is a feature and it makes it easier to control the output.

As for the show tools (groups/verses), you can drag the menu to the right and it will move to under the preview.

**Comment by dajomu1** [comment]
I think you missed my point. why does image in no. 1 show when I click on slide numbered 2 which has a black background? And, if I, being on no. 1, suddenly switch song which has no background image, why does image in no. 1 still gets presented? 

The show tools was easily moved. That was silly on my part :)

**Comment by vassbo** [comment]
I think I understood correctly, it's just hard to explain it in short. I will write some better documentation sometime with images explaining it. The slides are showing with a black background in the preview, but think if it as no background at all. It makes it easy to set one background image and use it for all of the shows. The background is independent of the show, when you click a slide with a background it just activates the background in the output (same as clicking the image in the media tab).

It's just something to get used to I guess. It's a feature also used by ProPresenter: https://learn.renewedvision.com/propresenter6/introduction-to-propresenter/presentation-layers

**Comment by dajomu1** [comment]
Sorry for nagging on this issue, but I think it makes more sense to do it like this. drag a background image to the slide you want and then a popup message asks if you want to apply only on this slide or all of them. Following the wysiwyg principle, it kinda breaks the logic to show a background on a slide that has no background. In the example below, if I want the first slide to have no background and the next two should have a background, I expect the same to happen if the song repeats and starts from the first verse again. But it doesn´t, it will keep the background from the last slide. This does not make sense to me.
![image](https://user-images.githubusercontent.com/98491691/195708538-30567352-74c3-43c1-89d9-fc97fda71fba.png)

**Comment by vassbo** [comment]
I think it's both good and bad sides with both methods. Maybe I'll add an option to change the behaviour. I'll have to think about what to do here. :)

(Det er litt morsomt at vi snakker engelsk til hverandre. Hvis du vil kan du skrive på norsk, men da er det kanskje ikke så lett for andre å lese som lurer på det samme.) 😁

**Comment by dajomu1** [comment]
Jeg valgte å skrive engelsk for at alle skal forstå 😊
