### ISSUE TITLE
Edit song, change text size

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#72]
tried to change text size on a song in different ways. Please see image enclosed
![image](https://user-images.githubusercontent.com/98491691/195168260-b7de52bd-b9b4-4ef4-b2d0-9f7d76a5b4db.png)

**Comment by vassbo** [comment]
Thank you for the good images. This is not added yet but I will do it sometime.

Right now there is an "Apply to all" button in the bottom right for applying styles to all slides in the show, or if you just want to change the style on a few slides you can create and drag a template slide over just the slides you want to apply the style.
