### ISSUE TITLE
copying slide by drag drop

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#73]
Sorry for commenting on a lot of things that I believe are bugs or lack of features. I find this project very interesting and I believe it fits or will fit my/church needs and we can replace easyworship altogether.
So todays bug/feature request is to have the possibility to copy a slide by ctrl-drag-n-drop. Now a copy icon pops up, but it actually just moves the slide. In order to copy, it seems like I have to make a copy and then move it.
The red square shows the icon appearing when dragging the slide
![image](https://user-images.githubusercontent.com/98491691/195314113-706b758c-d8a5-4e28-bf20-b8a8ef384950.png)

**Comment by vassbo** [comment]
No problem, thank you for all your feedback, it helps make the program better. :)

If you want to have multiple of the same slide you should drag the slide group from the right column, as shown here at 0:29: https://youtu.be/6zArghvgUok?t=29

Dragging should move the slide. If you want to clone a slide to make it different you can copy by ctrl+c -> ctrl+v or right click and duplicate. I might make it so you can hold ctrl while dropping to clone it.
