### ISSUE TITLE
Issues with showing scriptures +++

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#74]
I tried to use the scripture feature and I have found a few issues but I might just be a bit thick. 
1. The "max verse per slide" was set to 5, but this was not obeyed. The issue also persisted after I created a show of the scripture. ref. image attached
   a. I just figured out that this is mainly for the Header, text, blue header. The others were fine.
2. A double click on a verse will present it, but if you want more than one verse a show must be created? Lets say the pastor say he will read 3 verses, I create a show for that and then he suddenly wants to read 2 more? How can I easily add those? What would be nice is if I could double click on the first verse, hold shift and arrow down or click to just add more verses on the fly. If I see that the slide is overflowing, either the text will automatically adjust the text size or I can just click on the next verse and repeat the process.
3. When going to scripture I would very much like to have autofocus on the search field to avoid unnecessary mouse movement. That being said I am missing shortcuts and if they exist they could be shown by hovering the mouse over the the menu or something similar.
4. Where is the norwegian bible?
5. Going to the list of bibles, it would be great to have a search feature.
6. Possibility to show bible verses in two different languages

![image](https://user-images.githubusercontent.com/98491691/195716650-4e7e5a04-8c95-407e-a661-225e13aff25b.png)

**Comment by dajomu1** [comment]
just to clarify No. 5. I meant this list of bibles
![image](https://user-images.githubusercontent.com/98491691/195716967-ed0e345f-a187-45b9-9d50-3e3f3b8959a7.png)

**Comment by vassbo** [comment]
1. Hmm, I'll take a look.
2. To add more you can hold ctrl or shift to select multiple, and then press enter to show. Or you can just type the verses like this: John 1:1-10, in the search bar and press enter to show. If you press ctrl+arrow left/right you can move to the next/previous verses.
3. Might add shortcut tooltips sometime. You should be able to just press any letter key on the keyboard at any time and the drawer search should become active.
4. I have talked with API.Bible and they don't have the license/permission to distribute Norwegian bibles. But you should be able to find a few Norwegian xml bibles online, that you can import.
5. Good suggestion.
6. On the todo-list. :) You can do that with the mirror box feature, but maybe a bit tedious.

**Comment by dajomu1** [comment]
One more thing to add here: When searching it would be nice that the verses are shown. As you can see in the sceenshot, chapter and verse is not updated, only the book.
![image](https://user-images.githubusercontent.com/98491691/196045877-9f5f9555-46ac-4e3d-bca6-a744111f3b4f.png)
