### ISSUE TITLE
Import songbook from Videopsalm

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#77]
Hi,
Tried to import songbook from Videopsalm, but the instructions are not correct I believe. It is stated that one should find a .vpc file but it seems like VS is using .json. I tried to import the .json-file, but it did not work and I got no error message either.

![image](https://user-images.githubusercontent.com/98491691/197158980-5f994395-759a-46b5-b29a-50091de3ea60.png)

**Comment by vassbo** [comment]
Okay, it's probably a newer version using vps. Could you send over the json file not working so I can fix the issue?! 😊

**Comment by dajomu1** [comment]
[Familias Ecos.zip](https://github.com/vassbo/freeshow/files/9837771/Familias.Ecos.zip)
