### ISSUE TITLE
MIDI support

### ISSUE THREAD

**Issue by rauldipeas** [vassbo/freeshow#78]
Any chance to get MIDI support on Linux any time soon?

**Comment by vassbo** [comment]
It's on the todo-list. 😊

**Comment by vassbo** [comment]
The day is here!
Currently you can send out a MIDI note when pressing a slide.
But, please comment here if there is something you are missing. 😊

**Comment by rauldipeas** [comment]
MIDI in and out are supported?

**Comment by vassbo** [comment]
Current only out. But now it's easy to add in. But I need feedback how you would like it to work, because I don't know. Would you like it listen for a note, and play a slide for example? 😊

**Comment by vassbo** [comment]
MIDI inputs are here. It can play any slide, or go to next slide. Let me know how things are working in the latest version.
Or if you would like anything to change. 😊

**Comment by rauldipeas** [comment]
I've tried but I can't use it anyawy, the MIDI note, velocity and channel can't be setted manually, it always get note that came from another program.

I can't figure out how to use it.

I think that actions should be standardized inside FreeShow and You provide a chart with MIDI note or control change we need to send to trigger that action.

Control change MIDI information it's better than MIDI notes to trigger actions.

**Comment by vassbo** [comment]
Okay, thanks for the feedback. 😊 I'll try improving it.

**Comment by rauldipeas** [comment]
Thank You so much for this effort, FreeShow it's a great app.

**Comment by rauldipeas** [comment]
Great usability for now, I've made a quick test, I'll let You know when I'm going further.
