### ISSUE TITLE
expand button click area

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#86]
noticed that the areas shown marked with the mouse pointer does not accept button clicks. Other areas I have checked so far does so.
shortcuts image: hovering over the center of the "X" does not enable click. One must have the pointer in the lower regions of the "X".
![image](https://user-images.githubusercontent.com/98491691/210243802-bb9659e0-5399-4e68-9e48-e2a4b1a1f0fc.png)
Help menu: the clickable area does not extend all the way to the right, but on the other menus it does. Well apart from the View menu
![image](https://user-images.githubusercontent.com/98491691/210244140-fa51949c-244f-4f93-b6dc-6b0fb5839ad8.png)
![image](https://user-images.githubusercontent.com/98491691/210244215-35c032e4-8242-4228-b212-ea77313ad51a.png)

**Comment by vassbo** [comment]
Thanks. I don't have the "X" issue myself, but I will see if I can fix it. And the menu buttons.

**Comment by vassbo** [comment]
Do you still have this issue in the latest version?

**Comment by dajomu1** [comment]
All good now. At least in win10.
