### ISSUE TITLE
Search scripture

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#87]
Click on scripture tab does not automatically activate search feature. One must select text or similar before it is activated.
This requires an extra click.
![image](https://user-images.githubusercontent.com/98491691/210244590-a504ca22-77d1-41ca-8a3b-333c995f5aa4.png)

**Comment by vassbo** [comment]
Oh, I think the issue is that the drawer tab buttons are in focus. If you just click anywhere else on the screen it will be activated on keypress. But I will fix this.
