### ISSUE TITLE
Scripture - max verse per slide

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#90]
Setting max verse per slide does not work properly
![image](https://user-images.githubusercontent.com/98491691/210246591-6fe9c43e-7d90-43d3-bf19-751cfb5fe91c.png)

**Comment by vassbo** [comment]
This is the intended behaviour right now. If you set it to 4 and select 10 verses, it will create 3 slides with 4 or less on each slide. And you will have to change the template, or the text size to get it to show how you want to.
If I can get the auto size option to work here, that would probably be the best and most logical way to fit the text.

**Comment by vassbo** [comment]
Now if you enable "Auto size" in the template, it should change the text size automatically.
