### ISSUE TITLE
[(Minor) Bug Report] Shows are being savesd in the data folder root, instead of in the shows folder

### ISSUE THREAD

**Issue by yurividal** [vassbo/freeshow#909]
Not sure is this is a bug. Seems like it is.
All shows, including all songs, are currently stored in the root of the data folder, and the shows folder remains empty

![image](https://github.com/user-attachments/assets/90f9250f-4956-4216-8338-ec07d54d0cfa)

**Comment by vassbo** [comment]
Has you show data location been changed?
![bilde](https://github.com/user-attachments/assets/95e181e6-951c-4912-934c-2bac49b8422a)

**Comment by yurividal** [comment]
Oh, that was easy!
No, i hadn't changed it. I guess it was default to the root.

**Comment by vassbo** [comment]
This was still an issue and I figured out why!

I was returning the path from the `mkdirSync` function as I thought it returned the path of the created folder. But apparently it returned the path of the first created folder, or nothing if it already existed, which in most cases was the "FreeShow" directory. Meaning if it already existed and no folder was created it would return nothing, but fallback to the default "Shows" folder.
