### ISSUE TITLE
FreeShow Freezing up

### ISSUE THREAD

**Issue by rrsales** [vassbo/freeshow#91]
FreeShow keeps freezing up. I have to force close and lose all my work without being able to save. I'm running Mac Mini M1 With 8 GB Ram. I'm presenting to external tv screen. Please advise.

**Comment by vassbo** [comment]
It's probably a bug in the code. Could you explain what you are doing in the application right before it freezes?

**Comment by legounicycler** [comment]
I have found this to be a problem also, and I've traced it down to one particular group of slides in a particular show that I created while testing out this software for the first time. I haven't been able to recreate the process of creating this bug from a blank template, but I can consistently cause FreeShow to crash by
1. Transitioning past the problematic slide in my show
2. Attempting to open the edit tab in my show with the problematic slide
3. Changing the view in the "Show" tab to "Text Edit". This does not display any text like normal, but instead freezes the application entirely.

Deleting the particular group of slides from my show solves all these issues, and everything functions as normal.

Is there any value in uploading the file for the problematic show here as an attachment?

**Comment by vassbo** [comment]
Thank you. Uploading it will help me find the issue, so that would be appreciated. 😄

**Comment by legounicycler** [comment]
Thank you. I've uploaded the file in a zip. Hopefully it is something easily identifiable and not something to do with my configuration specifically. The slide group that seems to be causing problems is labeled "ErasmusCard". Trying to progress past slide 5 in the screenshot causes the freeze.

<img width="1280" alt="Screen Shot 2023-01-31 at 4 00 26 PM" src="https://user-images.githubusercontent.com/23005183/215882485-795cd806-998c-41da-8c5f-cb946aeebe39.png">


[Talk 01.26.23.show.zip](https://github.com/vassbo/freeshow/files/10550938/Talk.01.26.23.show.zip)

**Comment by vassbo** [comment]
Fixed the issue. It should no longer freeze, and it should fix itself.
If you are curious, the problem was that the show had a slide reference in the layout object, but the slide itself was missing for some reason, causing an error.
