### ISSUE TITLE
Scripture Bug

### ISSUE THREAD

**Issue by Jeddi212** [vassbo/freeshow#93]
I use scripture from local file (XML). When the scriptures were first opened, no problems arose. However, after I switch panels (to any panel), then return back to the scriptures from local files, there is only a loading animation (like forever). But there is no problem with the scriptures from "API.bible".

The XML file is linked below
https://drive.google.com/file/d/1hQIDaXrRakKyQnL8pQFt7FPpBXyhLBkQ/view?usp=share_link

<hr>

**Display when opening the scriptures from the local file for the first time.**
![image](https://user-images.githubusercontent.com/60323767/215283683-85e79a38-499b-40d8-9fa4-3c915b1724b3.png)

**Display when opening the scriptures from the local file after switching panel.**
![image](https://user-images.githubusercontent.com/60323767/215283710-f5c96ca9-776a-49bd-b793-d9aaf4cb941e.png)

<hr>

The reason i use local files, because i need specific version of the bible.

**Comment by vassbo** [comment]
Thanks, I'll look into it. Looks like there is some issue with the file name. 😊

**Comment by vassbo** [comment]
Should work now. The problem was the blank name.
