### ISSUE TITLE
Translate Quick Start Guide Titles

### ISSUE THREAD

**Issue by Ichthys88** [vassbo/freeshow#932]
The quick start guide looks good with its translated texts, but the titles of the guide still need to be added to transifex in order to be able to fully translate it.

For example, when I put Freeshow in Spanish, the texts are translated but since the titles are not, this makes it look like an incomplete translation and also makes the end user have to translate each title online in order to understand what specific area the guide is explaining.

https://github.com/user-attachments/assets/3ed6f009-1b0a-4599-94c6-fdb022b39983

**Comment by vassbo** [comment]
Yep, forgot about them.
