### ISSUE TITLE
working with scripture

### ISSUE THREAD

**Issue by dajomu1** [vassbo/freeshow#95]
Hi,

How can one show multiple lines from scripture without making it into a show first?
Scripture reading is often spontaneous and it can be difficult to know how many lines to include in the show. So it would be great that one somehow can make scripture going Live and show on projector immediately when selecting a verse. I know one can double click, but I would like to for instance select one verse and hold down shift and arrow down to just add more verses to the show. When the screen is full it should automatically adjust text size or make another slide or the person controlling can remove selection and start on the next verse and so on.
I tried to set the max verses per slide to 10 lines
selected 5 verses/lines and created a new show
I then added 4 more verses/lines and created a new show.
Problem: The 4 lines replaced the 5 lines in the first show instead of creating a new show. A new show is only created if one adds more than 10 lines.
![image](https://user-images.githubusercontent.com/98491691/215446319-89b65856-915e-4ba8-a061-d833a3d234ba.png)

**Comment by vassbo** [comment]
You should be able to hold ctrl+arrow left/right to change verses and press "Enter" to show. I think it might be broken right now though. Also the max verses per slide means how many bible verses are allow for ach slide, not lines. So you should reduce it to 3 or 4. Then you can select 10 verses and create a show if you want. I will add auto text size via the template option. 😊
