### ISSUE TITLE
[Bug Report] {RemoteShow is unstable on shows with audio}

### ISSUE THREAD

**Issue by Gonon-UP** [vassbo/freeshow#958]
I wanna say thank you for all the hard you all have been doing. This is one of my favorite software that I use and I love it very much. I upgraded to v1.3.0 from v0.9.4 and I recently found a bug in this new version.

**Describe the bug**
The bug is that, when on RemoteShow, a show with audio layered in the first slide takes a very long time to load and makes RemoteShow unusable. But when the show loads, sometimes there is no visible output in the RemoteShow browser along with the "Clear All" button not working (But taps will be reflected in the FreeShow preview), as it is grayed out or sometimes gone. RemoteShow works perfectly when I tap other any other show with no audio. 

**Reproducing**
Create a project with a show that has an audio layered in the first slide of the show. Connect to RemoteShow and tap on show with the audio. Not all audio files reproduce this problem, but I attached one that does.

**Version**
 - OS: I am running a desktop with Windows 10, 32 GB RAM, i5 11600KF, & GTX1080
 - RemoteShow Devices: Samsung Galaxy Tab S6 Lite running Android 13 with Firefox browser, Desktop Browser running Edge, Phone running Android 9 with DuckDuckGo & Firefox browser. Bug is reproducible on all 3 devices.
 - FreeShow Version: V1.3.0

**Additional context**
Attached are the 3 shows and a mp3 sample that reproduces this problem. I'm not sure why the bug happens but I noticed that removing the audio file doesn't make it better. New shows work fine but permanently break in the RemoteShow when I add the mp3, and are still broken when I remove the audio. "Mi Gozo" show is an example of this.

[Shows that reproduce the bug.zip](https://github.com/user-attachments/files/17596780/Shows.that.reproduce.the.bug.zip)

**Comment by vassbo** [comment]
Thank you! Got this fixed.

It tried capturing an image thumbnail from the audio file! 😅
