### ISSUE TITLE
Copy Paste In Show Editor Does not Work 

### ISSUE THREAD

**Issue by legounicycler** [vassbo/freeshow#96]
I am running FreeShow v0.6.3 on a Mac running OSX 11.5.2.

When I create a slide in a show, I select a subsection of text in a textbox, right click, and click copy from the dropdown menu, it instead copies the entire textbox. It doesn't seem that there is a way to copy paste individual characters or lines of text rather than the entire textbox. This is the same by using the keyboard shortcuts Cmd+C and Cmd+V

**Comment by vassbo** [comment]
Thanks, I will fix this! 😊
