### ISSUE TITLE
Cannot Drag or Right Click in the Media Bin when items are displayed in list view

### ISSUE THREAD

**Issue by legounicycler** [vassbo/freeshow#97]
I am running v0.6.3 on Mac OSX 11.5.2

I have added a folder to the media tab, and when the items in the folder are displayed in grid view, I can right click to see the context menu with no problem. I can also drag and drop them into a project without issues.

When I right click items in the media bin while they are displayed in list view, I get the context menu for the main program with dropdowns of "settings," "history," "about," and "quit."

As a related issue, there is a strange visual glitch which causes the size of the folder icon in grid view to appear very large and throw off the sizing of the grid, as shown below. Additionally, it would also be a very handy feature to have some hover text on grid items which show the file/folder name.
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/23005183/215873782-1189c9cf-75a9-4402-934d-525f9bb30948.png">

**Comment by vassbo** [comment]
Thanks for the feedback, I'll take a look. 😊

**Comment by vassbo** [comment]
Done. I figured that in list mode you can drag it, but just not from the name, you have to drag it from the image itself.
Trying to fix it caused some weird looks, so I choose to keep it like this, and hope that it's not going to be a big deal. 😊
