### ISSUE TITLE
Cannot add section to Project from Context Menu

### ISSUE THREAD

**Issue by legounicycler** [vassbo/freeshow#98]
Running v0.6.3

In the lefthand window (not sure if they have names), I have selected a project. Right clicking brings up a context menu with two options, "New Show" and "New Section". The "New Show" option works as expected, but the "New Section" option does not do anything when clicked.

<img width="1280" alt="Screen Shot 2023-01-31 at 4 10 29 PM" src="https://user-images.githubusercontent.com/23005183/215884268-67beadd6-83a9-4aa5-94ef-75706a409cf1.png">

**Comment by vassbo** [comment]
Oh. Thanks, I will fix this! 😊
